### ISSUE TITLE
Rspec after hook being called before spec finishs

### ISSUE THREAD

**Issue by rafaels** [teamcapybara/capybara#1089]
I am having trouble with a scenario where I only do:
- click_link, which will fire an ajax request
- find something
- on a after(:each), I run DatabaseCleaner.clean

The problem is, the ajax request is running at the same moment of the after(:each) block, which causes me to have a nil association in the model code. 

It is the real issue. I think that if I have a spec, it's after hooks should only run after all requests from this test are terminated. In my case I was getting controller and model code running at the same time as my DatabaseCleaner.clean, driving me to random errors when associations were not at the database anymore.

I think it is a way important issue, cause I heard from people problems that fits it.

For example, if I have an js: true spec and inside this spec I interact with the page and some ajax requests are fired, but my spec isn't testing this specific ajax requests, this problem can easily arrive. Say this ajax request is slow and the real spec finished without needing the response from this ajax. The example will pass at the beginning but the ajax will fail the example later because it needs somethings at the database.

Please, if I can help more, get in touch.

I am using capybara + rspec + poltergeist.

PS. I resolved my problem with a better find, which will only be true when the ajax request returns and js renders the stuff. But this 'issue' showed me the above issue.

**Comment by ka8725** [comment]
The problem arises because Capybara's hook in Rspec is executed before others. In my case it was `DatabaseCleaner`'s after hook and it was truncating the database randomly. BTW, `around` hook not worked for me either. So my solution is very simple - just past capybara's initial stuff into bottom of `spec/spec_helper.rb` file:

```ruby
ENV['RAILS_ENV'] ||= 'test'
require File.expand_path('../../config/environment', __FILE__)
require 'rspec/rails'
# Require here support files, other gems and init some other stuff
RSpec.configure do |config|
end

require 'capybara/rspec'
require 'capybara/poltergeist'
Capybara.javascript_driver = :poltergeist
# Other configuration of Capybara
```
Hope it helped you either.

**Comment by richkettle** [comment]
Im having the same issue. 
It seems focused around a single example. Im 99% sure the example is fine:

````ruby
context 'package details' do
  before do
    step_though_questions
  end
  
  it 'lets you through to the thank you page' do
    # submit package
    page.find(".standard_package.btn.btn-default").click

    fill_in_customer_details(self)
    # submit customer details
    page.find('.btn.btn-block.btn-call-to-action.green').click
    expect(page).to have_content(/Thank you/)
  end
end
````
````ruby
def fill_in_customer_details
  fill_in("full_name", with: "Tester McTesterson")
  fill_in("address_building_name_or_number", with: "12")
  fill_in("address_postcode", with: FactoryGirl.generate(:postcode))
  fill_in("email", with: FactoryGirl.generate(:email))
  fill_in("landline", with: FactoryGirl.generate(:phone_number))
end

def step_though_questions
  visit '/new-thing'

  labels = ["label1", "label2", "label3", "label4"]

  # click through to the customer details step
  labels.each do |label|
    page.find("label[for=#{label}]").click
  end
end
````
Tried all the methods here. Around hook, moving the include still no luck.

    capybara (2.4.1)
    capybara-webkit (1.4.1)

Truncate setup looks like:
````ruby
RSpec.configure do |config|
  config.before(:suite) do
    puts "set to truncate"
    DatabaseCleaner.clean_with :truncation
  end

  config.around(:each) do |example|
    puts "around each start"
    if example.metadata[:type] == :feature
      puts "its a feature spec!"
      DatabaseCleaner.strategy = :truncation
    else
      puts "its NOT a feature spec!"
      DatabaseCleaner.strategy = :transaction
    end
    example.run
    puts "DatabaseCleaner.start"
    DatabaseCleaner.start
    puts "around each end"
  end

  config.after(:each) do
    puts "DatabaseCleaner.clean"
    DatabaseCleaner.clean
  end
end
````

In my debugging I have found that the `/new-thing` visit either happens twice or the `new` action on the controller is being called twice. Logging looks like:

````
set to truncate
around each start
its a feature spec!
in new action
trying to find something
after finding the thing
DatabaseCleaner.clean
in new action
trying to find the thing *Error occurs here and fails the spec*
DatabaseCleaner.start
around each end
````

I have accidentally stumbled across two solutions but I have no idea how or why either of them work. 

The first one was in the controller action. Where I was getting the no method error on foos.

    @foo = Foo::FooType.find_by(:slug => foo_slug).foos.build

became

    @foo = Foo::FooType.find_by!(:slug => foo_slug).foos.build

The bang seemingly makes the spec pass 100% of the time????

The other solution I ~~came up with~~ found was to add `page.save_screenshot('screenshot.png')` after the `expect` line of the spec. I'm not sure how or why I put it there, I just did. I did read somewhere that you should always check for something on the page at the end of a spec like this so that capybara waits and starts the next example correctly. It may have something to do with it.

This might help get to the bottom of the problem or at least help someone.

**Comment by mkllnk** [comment]
We are using Capybara 2.2.1 with Poltergeist 1.5.0 and had deadlocks in feature specs. The problem were unfinished Ajax calls at the end of the spec. The database cleaner tried to change stuff that was still in use.

Our current solution was finding all Ajax calls and waiting for them to finish. That's not ideal and I'm thinking of implementing this: http://blog.salsify.com/engineering/tearing-capybara-ajax-tests

Any better ideas?

**Comment by kbaum** [comment]
We use an especially after hook that hits a simple page that has no Ajax. This causes capybara to wait until Ajax is complete within the actual spec.

**Comment by mkllnk** [comment]
Is that the same as this?
```ruby
config.after(:each) do
    Capybara.reset_sessions!
    DatabaseCleaner.clean
end
```

And isn't there still the case that a request was cancelled but the server is still busy completing the request? We have some computations that take a bit longer...

I'm using a slightly modified version of the [rack request blocker](https://gist.github.com/mkllnk/e3805dd7d566e6b1176c) from [salsify](http://blog.salsify.com/engineering/tearing-capybara-ajax-tests) in spec_helper.rb:
```ruby
  config.after(:each, js:true) do
    Capybara.reset_sessions!
    RackRequestBlocker.wait_for_requests_complete
    DatabaseCleaner.clean
  end
```

It has been working fine, but increased the run time of the test suite by maybe 5%.

**Comment by nambrot** [comment]
Has anyone ever found an explicit reason for this failing. For our most recent tests, RSpec seems to induce the teardown by DatabaseCleaner before everything has finished, but for the life of me I cannot figure out why

**Comment by twalpole** [comment]
@nambrot  It's generally caused by ajax requests that don't complete before the test finishes -  Capybara does not know about these requests since the app is running separately and therefore doesn't wait for them to finish -  There is no universal solution to this (other than maybe using a proxy to detect requests) - but if you know that all your ajax requests are using a specific library (jQuery, etc) then you can add an after hook to wait for the request count to be 0 before continuing

**Comment by nambrot** [comment]
@twalpole 

> but if you know that all your ajax requests are using a specific library (jQuery, etc) then you can add an after hook to wait for the request count to be 0 before continuing

I presume you mean to put this in the after hook where I use DatabaseCleaner?

I have a test case such as 
`expect { action }.to change{ ActionMailer::Base.deliveries.count }.by(1)`

**Comment by twalpole** [comment]
The after hook checking for ajax requests would need to execute before reset_sessions! is called (added in capybara/rspec if youve included that) and also before DatabaseCleaner after hook. The problem is that it's really a hack and has a number of weak points , such as the minute you add a JS library that creates native XHR requests , rather than going through jQuery, it no longer works, and if a request is initiated after you check but before the browser session gets reset it no longer works.  It's much better to wait for a visible on screen change if possible.

**Comment by nambrot** [comment]
>  It's much better to wait for a visible on screen change if possible.

Inside the test or before the after hook in a separate after hook? Most of my tests check for screen changes, but the after hook for cleanup will still be called beforehand unfortunately

**Comment by jrochkind** [comment]
@jnicklas [says](https://github.com/jnicklas/capybara/issues/1089#issuecomment-26678773):

> So I added 6b1e42d, which should hopefully make sure that reset is always synchronous. This plus ensuring the hooks are called in the right order, should resolve this issue.

It is not clear to me the proper/supported/best-practice way to "ensure the hooks are called in the right order" with capybara and database cleaner. 

I _think_ I am running into this problem.  Should DatabaseCleaner and/or Capybara docs be enhanced to explain the necessity of ensuring the hooks are called in the right order, and how to do that?

**Comment by twalpole** [comment]
@jorchkind  The order hooks are called in is not a feature of Capybara or DatabaseCleaner, its defined by the test framework you're using - rspec, etc.  As for the proper/supported/best-practice way, that needs to be defined by the programmer with a knowledge of what their app does.  I'm locking this issue now, if you have questions on how to make things work with Capybara please ask them in the mailing list as requested in the README and CONTRIBUTING files.
