### ISSUE TITLE
Please raise error when attempting to set readonly textfield

### ISSUE THREAD

**Issue by Confusion** [teamcapybara/capybara#1178]
When a textfield has been marked 'readonly' and you call e.g. `fill_in('text_field_id', with: value)`, it fails silently. `Capybara::RackTest::Node#set` simply does not execute the `set`, because of an `unless self[:readonly]`. Please raise an error if this is attempted: it would have saved me quite some time searching for why the `set` didn't work. I'm sure others have been surprised by this as well.

**Comment by davout** [comment]
It would be very nice to have the option of ignoring the "readonly" property and override this behaviour altogether.

While I understand the rationale behind replicating user interactions it still feels extremely wrong to install, and deal with the complexity (locally and in the CI environment) of a JS driver stack for the sake of hacking an `execute_script` into filling a date picker. (which, by the way, isn't that much closer to replicating actual user behaviour than simply having the ability to force a readonly field).

Cheers!

**Comment by twalpole** [comment]
@davout Since it sounds like you're using the rack_test driver you can just do `element.native['value'] = 'whatever to set'` if you really really want to set a readonly element.  The bigger question is why you would want to be setting a readonly element since a user couldn't, and even if you were using a JS capable driver you should be setting it the same way a user would rather than using execute_script
