### ISSUE TITLE
Capybara does not fill input[type="number"]

### ISSUE THREAD

**Issue by abezzub** [teamcapybara/capybara#1304]
With latest update to selenium webdriver 2.41.0 and Firefox 29 setting of number fields (input[type="number"]) does not seem to work any more:

```
require "capybara"

html = DATA.read
app = proc { |env| [200, { "Content-Type" => "text/html" }, [html] ] }

sess = Capybara::Session.new(:selenium, app)
sess.visit("/")

sess.find(:fillable_field, "abcd").set(1)

sleep(10)

__END__

<!doctype html>
<html>
  <body>
    <input id="abcd" name="abcd" type="number">
  </body>
</html>
```

Input field remains empty.  If I change `type="number"` to `type="text"` then "1" is set to the input. Is this a known problem?

**Comment by gabeodess** [comment]
workaround if you are using Poltergeist:

```javascript
evaluate_script("$('#{selector}').val(1)")

**Comment by twalpole** [comment]
@gabeodess This issue was specifically about using selenium, and closed over a year ago.  If you are saying that Poltergeist won't fill a visible input of type number, please file an issue over on the poltergeist project.  Generally, suggesting javascript execution as a workaround is usually a terrible idea since the app is no longer being tested as a user would interact with it, doesn'tt generate events, etc. Yes there are times when it can make sense, but that usually involves really understanding why you're doing it which a lot of beginning capybara users don't.

**Comment by gabeodess** [comment]
@twalpole this was the first hit I got when I was trying to figure why my number fields weren't filling with capybara's #fill_in method.  I figured I would just include how I got around this in case other people got to this same thread.
