### ISSUE TITLE
Unicode spaces shouldn't be normalized

### ISSUE THREAD

**Issue by abotalov** [teamcapybara/capybara#1353]
HTML 5.1 (http://www.w3.org/TR/html51/single-page.html#space-character) defines two methods for normalizing spaces:
- "skip whitespace" (that normalizes just 5 characters)
- "skip White_Space characters" (that normalizes all Unicode spaces)

Only the first of those algorithms seems to be actually used in the spec.

XML defines only 4 characters as one that should be normalized - http://www.w3.org/TR/xml/#NT-S

See https://gist.github.com/abotalov/19f6f07b2d9cc64f8a59 (HTML), https://gist.github.com/abotalov/df3630771e21bae504c8 (XML) for my evaluations.

What should be changed? (please approve. I think it can be changed in 2.x as it's a bug)
1. `Capybara::Selenium::Node#visible_text` shouldn't do space normalization as Webdriver already does it - https://dvcs.w3.org/hg/webdriver/raw-file/default/webdriver-spec.html#widl-WebElement-getElementText-DOMString)
2. Algorithm of `normalize_whitespace` itself should be changed to do space normalization similarly to how getElementText does it. Some parts of getElementText's algorithm (e.g. processing CSS whitespace style) aren't worth to be checked so the algorithm will be somewhat different.

Initially `normalize_whitespace` was made to handle so many space characters after https://github.com/jnicklas/capybara/issues/767. But it seems to me that this issue is entirely different (or code has changed too much as currently `normalize_whitespace` has nothing to do with `find_link`). Normalization for `find_link` happens in `xpath` gem and #767 is still not fixed and should be fixed there (this is an attempt - https://github.com/jnicklas/xpath/pull/63, however it's incorrect as it shouldn't treat several nbsp as one)

**Comment by twalpole** [comment]
With 3.0 release coming up, I probably need to look at this -- Does anyone have any examples of where Capybara is doing the wrong thing currently and what the correct results should be?

**Comment by abotalov** [comment]
Well, I didn't check it since writing this issue.
But I think the issue is that when HTML contains "a&nbsp;&nbsp;b", Webdriver returns text "a  b", but Capybara returns "a b".

**Comment by elliterate** [comment]
(For those reading on a mobile device, that's two `&nbsp;` codes in the HTML, two standard space characters returned by WebDriver, and one standard space character returned by Capybara.)

**Comment by twalpole** [comment]
Ok -- so the space/&nbsp issue is easy enough to handle correctly, the real problems are the `\n` put in by webdriver for block level elements.  This causes an issue with rack_test since we don't really know when elements have their display mode changed to be block/block equivalent (no real CSS processing) and/or their whitespace behavior is changed.  We can just go with adding `\n` for elements that default to block display type and there will be a discrepancy between rack_test and real browser (as there is for other things affected by CSS), we can just ignore the `\n` for rack_test, or we can replace all `\n` with spaces (and collapse) from all the drivers - thoughts?

**Comment by twalpole** [comment]
Hmmm -- the `\n`s are also an issue for non-visible text in selenium (and probably other drivers)
