### ISSUE TITLE
#text value of node found returns empty string if ignore_hidden_elements is true

### ISSUE THREAD

**Issue by tmertens** [teamcapybara/capybara#1394]
Take for example an element which has the text content `The quick brown fox jumps over the lazy dog`, the locator '.content-test', and is not visible.

If `ignore_hidden_elements` is set to `true` (the default), then the following methods will return incorrect results on the element when found with the query option `visible: false`:

``` ruby
# This should return "The quick brown fox jumps over the lazy dog"
find('.content-test').text
#=> ""

# This should return true
find('.content-test').has_content?("The quick brown fox jumps over the lazy dog")
#=> false
```

However, the following would succeed:

``` ruby
find('.content-test', text: "The quick brown fox jumps over the lazy dog")
#=> #<Capybara::Element>
```

I have not investigated what other methods may also be affected by this issue.  The resolution for me was to set `ignore_hidden_elements = false`.

**Comment by wingice** [comment]
Run into the same issue today.

In my opinion , we already include "visible: false" in [find('invisible-element', visible: false).text], so don't need to repeat the similar option (:all) in text(:all).

**Comment by twalpole** [comment]
This isn't changing.  You have to specify what visibility you want in the text marchers.  Is this inconvenient? Maybe, but that's because you probably shouldn't be testing for text content of invisible elements.  If the user can't see it why are checking for its text content?  If the user will be able to see it at some point then then trigger whatever behavior makes it visible and test its content then.  If you really, really, really want to be testing text content of invisible elements a lot, then write a helper method to make it easier for yourself

**Comment by Nakilon** [comment]
`text(:all)` solved this for me but I support @wingice.  
My case was a error balloon outside of browser window because the page is too wide.

**Comment by twalpole** [comment]
@Nakilon If your error balloon is appearing offscreen, then thats a usability issue and should be fixed, rather than changing your text to pass when the text is not visible -- hence why you shouldn't be searching for things that aren't visible.
