### ISSUE TITLE
Using capybara to test Google Polymer as front end

### ISSUE THREAD

**Issue by afterclassroom** [teamcapybara/capybara#1411]
We are developing a web app using Google Polymer as front end.

We discovered that Capybara could not query element within Shadow DOM.

Is there any technique to solve this?

**Comment by maxkerp** [comment]
This issue is old, but since it's the first result when you search for "capybara testing polymer" i want to leave some notes for the next poor soul who is looking for a way to test web-components with capybara.

1. Your tests need to be flagged `:js`. Duh, I know. But maybe I'm not the only one who makes dumb mistakes.
2. Since you're now writing `:js` specs, you have to decide on a driver. Phantomjs (poltergeist) apparently does not support web-components. I use `selenium-webdriver` and registered chrome as a browser.
3. Using chrome with `selenium-webdriver`(gem) requires `chromedriver`(system binary) to be installed on your machine. You can find it here:
https://sites.google.com/a/chromium.org/chromedriver/downloads
Make sure it's in your PATH and it has permission to be executed (`chmod +x`)
4. Add this to your `rails_helper.rb` (if you're using rails)
```ruby
Capybara.register_driver :chrome do |app|
  Capybara::Selenium::Driver.new(app, :browser => :chrome)
end

Capybara.javascript_driver = :chrome
```

This means your tests won't be headless, but feel free to get this set up and working with headless chrome. If you do, tell me about it :)
Fields and Inputs should be easily reached with:
```ruby
fill_in "id_of_input_in_component"
click_on "Text of Submit Button in Component"
```

**Comment by twalpole** [comment]
@maxkerp Assuming you're using current Capybara (2.15.1 as of now) you don't need to register your own driver for this, just specify either

    Capybara.javscript_driver = :selenium_chrome

or

    Capybara.javascript_driver = :selenium_chrome_headless

**Comment by hraynaud** [comment]
@maxkerp what about the primary issue of finding elements within the shadow dom?  Your comment doesn't address that at all.
