### ISSUE TITLE
Capybara loses hash parameters in document.location.hash

### ISSUE THREAD

**Issue by aminariana** [teamcapybara/capybara#1837]
## Meta
Capybara Version:
2.12.1
Driver Information (and browser if relevant):
all defaults

## Expected Behavior
Be able to assert:
```
expect(current_url).to eq "http://callback.google.com#code=magic"
```

## Actual Behavior
Assertion fails, because `current_url` does not contain the `#code=magic`
```
puts current_url
# http://callback.google.com
```

## Steps to reproduce
Visited a URL that redirects to a url like: "http://callback.google.com#code=magic"
(Note: This is part of the standard OAuth 2.0 protocol, not an unusual spec that should need JS.)

Related: #155

**Comment by twalpole** [comment]
1. You don't state what driver you're using
2. You should never use the 'eq' matcher with current_url (if you want stable tests), thats what the have_current_path matcher is for
3. If you don't need JS, are you using the rack-test driver?? If so that doesn't support visiting any URL outside the local app under test (host is ignored) so it's no surprise you're having issues.
4. Steps to reproduce needs to be steps that will actually reproduce the issue - like

        require 'capybara/dsl'
        require 'selenium-webdriver'
        include Capybara::DSL
        Capybara.default_driver = :selenium 

        visit('something')
        assert_current_path('http://something...', url: true)

**Comment by twalpole** [comment]
Closing, we will reopen if/when enough info to reproduce is provided.
