### ISSUE TITLE
can't find element with webkit

### ISSUE THREAD

**Issue by majioa** [teamcapybara/capybara#1838]
**Note:** This is for issues with Capybara.  If you have a howto type question, please ask on the mailing list as requested in the README: http://groups.google.com/group/ruby-capybara

## Meta
Capybara Version:

2.7.0
Driver Information (and browser if relevant):

capybara-webkit 1.11.1
qt 5.0
qt5-webkit-common-5.6.2-alt0.M80P.1

## Expected Behavior
`fill_in('email', with: @user.email)` finds the input element

## Actual Behavior
`Capybara::ElementNotFound`

## Steps to reproduce

the code:
```
        <div class="input-wrap">
           <input aria-required="true" autofocus="autofocus" class=" b-input b-input__m_text required" data-email-healing="true" id="user_email" name="email" placeholder="Email" size="30" spellcheck="false" tabindex="1" type="email">
        </div>
```

**Comment by twalpole** [comment]
Capybara-webkit is a driver that can be used with Capybara and is located at https://github.com/thoughtbot/capybara-webkit .  If this issue is capybara-webkit specific then you'll need to discuss it over at that project.  The first thing they will likely tell you to do is to update to the latest release of both capybara-webkit and capybara, and then to make sure the element is actually visible on the page you think it is (via a screenshot) so you may want to perform those two steps before reporting an issue over there.
