### ISSUE TITLE
click_link returns but does not click link when browser window is not visible

### ISSUE THREAD

**Issue by rbu** [teamcapybara/capybara#1839]
## Meta
Capybara Version: 2.12.1
Driver Information (and browser if relevant): selenium-webdriver 3.1.0 with Firefox 51

## Expected Behavior
When a ``click_link`` returns successfully, the link is being clicked.

## Actual Behavior
The ``click_link`` returns, but the link is not clicked.

We have been observing this problem in one of our apps where we navigate through clicks and Firefox would not load the clicked pages. In the app, this was simple a-href links. This happens on our AC server where we run multiple browser sessions during one test in an Xvfb and windows are maximized. The browser which was not in front would simply start misbehaving. We were able to reproduce and minimize this problem locally by using one browser and minimizing the window (on Linux). However, it only seems to happens on pages that execute heavy JavaScript.

## Steps to reproduce
```rb
require 'capybara'
require 'capybara/dsl'

require 'selenium-webdriver'

Capybara.default_driver = :selenium
Capybara.app_host = 'http://coderthemes.com/minton_2.1/blue/index.html'
Capybara.run_server = false
Capybara.default_max_wait_time = 20

include Capybara::DSL
visit ''

puts('Minimize browser window now')
sleep 3

3.times do
    click_link('UI Kit')
    click_link('Buttons')
    puts("Loaded Buttons page #{has_text?('the button classes on an')}")
    click_link('Dashboard')
    puts("Loaded Dashboard page #{has_text?('Total Sales today')}")
end
```

**Comment by rbu** [comment]
![cut](https://cloud.githubusercontent.com/assets/65913/23401961/ebfc75d0-fda9-11e6-828a-0bc323f272f7.gif)

**Comment by dwt** [comment]
I would like to add that we have manually inserted a ```page.driver.switch_to_window('')``` whenever we switch browsers, which seems to have made this problem at least happen less often. However, I'm not yet convinced it is a workaround, as we still have test flakiness which might originate from this bug.

**Comment by rugill** [comment]
I've been having similar problem with Capybara2 with recent FF and chrome drivers. What I have observed is that if an element is not visible in the browser window (i.e. needs scrolling down), then it does not get clicked even though capybara finds it. You can reproduce this issue by making the window small such that an element is not visible. I added a click to "Maps". If the window shows Maps link the automation run successfully. If I make the window such that Maps is not visible it fails with this error:
  unknown error: Element <a href="javascript:void(0);" class="waves-effect waves-primary">...</a> is not clickable at point (35, 24). Other element would receive the click: <i class="md md-equalizer"></i>
        (Session info: chrome=56.0.2924.87)
        (Driver info: chromedriver=2.27.440174 (e97a722caafc2d3a8b807ee115bfb307f7d2cfd9),platform=Mac OS X 10.12.3 x86_64) (Selenium::WebDriver::Error::UnknownError)
      ./features/reports/step_definitions/reports_steps.rb:702:in `block (2 levels) in <top (required)>'
      ./features/reports/step_definitions/reports_steps.rb:701:in `times'


  3.times do
      click_link('UI Kit')
      click_link('Buttons')
      puts("Loaded Buttons page #{has_text?('the button classes on an')}")
      click_link('Dashboard')
      puts("Loaded Dashboard page #{has_text?('Total Sales today')}")
      click_link('Maps')
  end

**Comment by twalpole** [comment]
@rugill If that is the issue then it would be a selenium bug and not much Capybara can do about it - although I don't know why adding sleeps would make it pass then (unless the page is animating something as selenium scrolls it so the click ends up in the wrong place - would still be a selenium bug)

**Comment by twalpole** [comment]
@rugill I just noticed the point (35, 24) that it's trying to click at.  That point would put it behind the fixed header so I would expect another element to receive the click, i.e. it's behaving correctly.  The thing is that when an element needs scrolling to be seen selenium attempts to scroll it to the top of the page, there's a capability 'elementScrollBehavior' that you can set to 1 which will make it scroll to the bottom of the page (if chromedriver has implemented that capability), although that may not help here either due to the fixed footer in the section which it would probably end up under.  Your only option may be to scroll the section of the page to where you need it using `execute_script` and then click the link

Either way this isn't the same problem as the current issue.

**Comment by rugill** [comment]
I've been doing more testing with this and I agree with @twalpole conclusion. I'll check into his suggestion about elementScrollBehavior with FF and see if it helps my test. Thanks.

**Comment by rbu** [comment]
@twalpole thanks for the feedback. While the page I linked has animations, I have been able to reproduce this issue on a page that has no animated menu as well, but since it's not a public application, I cannot share that link unfortunately.

The reason this is confusing to me is that even if the animation is running slower, I would expect it to *not find* the link. On the other hand, if the link is actually found and clicked, why is the click not being triggered?

In our local example, we were able to reproduce this in Xvfb and a ratpoison window manager which automatically full-screens the Firefox. Then we would:
1. Open Firefox A, navigate to a page
2. Open Firefox B, this hides Firefox A completely
3. In Firefox A session, navigate to another page, then click a link.

The result will be: The click brings Firefox A into the foreground (!) and there is a hover effect over the link/button. But it was not clicked.

**Comment by twalpole** [comment]
@rbu I can't say 100% for sure without a lot more debugging of that page but it appears the menu is swallowing all other clicks while it's animating, so the click is actually happening it's just not triggering any actions.  Then adding a sleep delays enough that the animation has finished and the click is no longer swallowed by the menu.

Your second description would most likely be a geckodriver/marionette issue if the browser is behaving differently when in the foreground or not, and Capybara probably can't do anything about it.  One thing you could try is making sure the 'focusmanager.testmode' preference is set to 'true' in the firefox profile.  I know Selenium used to set that, but I don't think it does since the swap to using geckodriver/marionette, and am not sure whether firefox even supports it anymore but doesn't hurt to try it.

**Comment by rbu** [comment]
@twalpole, Thank you for the feedback. As I mentioned, I was not able to reduce the core Firefox/Selenium issue further so it could become a good bug report. I'll close this for now, as you point out it is not a Capybara issue.

As a sidenote, do you know if Selenium accepts bugs written using the Capybara API?
