### ISSUE TITLE
README instructions is missing a required step for rspec

### ISSUE THREAD

**Issue by jasonfb** [teamcapybara/capybara#1854]
In my Rails 5 app, this line is necessary inside of the ```RSpec.configure do |config|``` block

```
config.include Capybara::DSL
```

however, this step is missing from the README instructions under https://github.com/teamcapybara/capybara#using-capybara-with-rspec

**Comment by jasonfb** [comment]
without this I get ```no method visit for ....```

**Comment by twalpole** [comment]
As mentioned in the section you linked to,  the only thing necessary to do to use Capybara in feature specs, and the matchers in view specs, is `include 'capybara/rspec'` which includes Capybara::DSL into tests with `type: :feature` - https://github.com/teamcapybara/capybara/blob/master/lib/capybara/rspec.rb#L8

If you're trying to use Capybara in tests that aren't `type: :feature` then you're using it in a non-recommended/non-supported manner and will need to include Capybara::DSL into those tests yourself.  Even in that case you should only be including Capybara::DSL into the test types you want to use it in, and not into every single test you have, otherwise you're asking for problems.

**Comment by jasonfb** [comment]
Does not work. I already have ```include 'capybara/rspec' ``` in my spec_helper.rb file, and when I set my specs to use ```feature: true``` I still get 
```
 Failure/Error: visit @base_url
     
     NoMethodError:
       undefined method `visit' for #<RSpec::ExampleGroups::AddToCart:0x007fec1000bc80>

```

this should be reproducible on a fresh new Rails installation, so there is no point in debating it. I will put together a simple reproduction example and push it to Github as evidence.

**Comment by jasonfb** [comment]
You seem to be right, I cannot reproduce this on a new Rails 5.0 installation.

**Comment by twalpole** [comment]
@jasonfb  You need the metadata.  `:type => :feature` to get set on the test, not 'feature: true'
