### ISSUE TITLE
Why was #1860 locked?

### ISSUE THREAD

**Issue by openscript** [teamcapybara/capybara#1889]
Hey all

I was following the discussion in #1860. Why is it locked now? Where is the right place to discuss it?

Thanks.

**Comment by twalpole** [comment]
#1860 Was locked because it was going off topic and there is no new information at the moment.  When the next release of chromedriver/chrome is released we will update the thread with the current status.  Until then, if you have specific questions on how to do something ask on the mailing list, gitter, or stackoverflow
