### ISSUE TITLE
Allow sectioning big feature specs for better spec documentation

### ISSUE THREAD

**Issue by joefiorini** [teamcapybara/capybara#1894]
This is a feature request. I want to get a general 👍 on the idea before putting in the work to patch it.

We have a large feature spec suite and some of our feature specs get fairly large. It is a constant balance between minimizing the number of page interactions (to keep tests fairly quick) and having small examples that are well-documented. One thing that would drastically help this is to being able to have "sections" within examples that exist purely for documentation purposes. The implementation would be pretty much [as described here](https://cloverhound.com/2017/06/07/making-rspec-feature-tests-more-semantic-by-dividing-scenarios-into-sections/).

I am opening this here because I agree with @cupakromer on rspec/rspec-rails#1352 that since Capybara already implements a feature spec DSL for rspec, this is the appropriate place for such a feature. I'm happy to open a PR, but want to make sure others agree this is the right place.

Thoughts?

**Comment by twalpole** [comment]
The Capybara `feature` spec "DSL" is just an alias for passing `type: :feature` to RSpecs `it`

    feature "my test"   => it  "my test", type: :feature

we really don't add any functionality or behavioral changes to RSpec.  

Your feature sounds like it would be better implemented as its own gem (`rspec-sections` or similar) rather than added into Capybara.
