### ISSUE TITLE
Capybara doesn't seem to be reinitializing

### ISSUE THREAD

**Issue by maxiedaniels** [teamcapybara/capybara#1906]
Using capybara 2.15.1, selenium gem 0.2.11, with chrome-driver 2.30.

I'm having an issue where I'll run a test, and then try and reinitalize my driver with a new proxy and re-run the test, but it's not actually switching proxies. I've tried doing reset_sessions! but no dice so far..

```
Capybara.register_driver :selenium do |app|
		Capybara::Selenium::Driver.new(app, :detach => false, :browser => :chrome, :switches => ["--proxy-server=#{aProxy}"])
end
session = Capybara::Session.new(:selenium)

[testing goes here]

Capybara.reset_sessions!

Capybara.register_driver :selenium do |app|
		Capybara::Selenium::Driver.new(app, :detach => false, :browser => :chrome, :switches => ["--proxy-server=#{aProxy}"])
end
session = Capybara::Session.new(:selenium)

[more testing, but proxy should change and doesn't]
```

**Comment by twalpole** [comment]
`reset_sessions!` wouldn't affect this at all.  It resets all Capybara managed sessions back to about:blank and clears cookies.  Since you're manually creating your sessions they aren't managed by Capybara and shouldn't be touched by `reset_sessions!`.   

Are you actually using `session` in your testing? Please show part of `[testing goes here]`

Have you tried registering the second driver with a different name, and then creating the second session with the newly registered driver instead of reregistering?

Additionally, you're passing `:switches` which is deprecated in current releases of selenium-webdriver, what version of selenium-webdriver are you using?
Chromedriver 2.31 is out, have you tried updating?

**Comment by twalpole** [comment]
Closing due to lack of response
