### ISSUE TITLE
Capybara issues with headless chrome

### ISSUE THREAD

**Issue by tomdracz** [teamcapybara/capybara#1908]
## Meta
Capybara Version:
2.15.1
Driver Information (and browser if relevant):
selenium-webdriver 3.5.1 with Chrome 60 headless with Chromedriver 2.31

## Issue
I've tried to migrate my test suite to run headless Chrome instead of Poltergeist and started getting some random errors. Headless chrome is configured like:

```
Chromedriver.set_version "2.31"

Capybara.register_driver :chrome do |app|
  Capybara::Selenium::Driver.new(app, browser: :chrome)
end

Capybara.register_driver :headless_chrome do |app|
  capabilities = Selenium::WebDriver::Remote::Capabilities.chrome(
    chromeOptions: { args: %w[headless disable-gpu] }
  )

  Capybara::Selenium::Driver.new app,
                                 browser: :chrome,
                                 desired_capabilities: capabilities
end

Capybara.javascript_driver = :headless_chrome
Capybara.raise_server_errors = false
```

## click_link
Got erb code like
```
<div class="row">
  <div class="col-lg-12">
    <%= link_to "CSV", admin_bookings_path(format: "csv", params: { data_table_id: params[:data_table_id], q: params.to_unsafe_h[:q] }), class: "btn btn-warning" %>
  </div>
</div>
```
In test I'm calling it like:
```
visit admin_bookings_path
expect { click_link('CSV') }.to change(Admin::BackgroundSearchCsv.jobs, :size).by(1)
```
That assertion fails, but putting debugger in the controller, I can verify that this click never happens, controller is never hit.
This however works:
- in Poltergeist
- in non-headless Chrome
- if I put sleep 1 before click_link
- and bizzarely enough, if I change link text and assertion to "CSVeee". If I only change the link, the assertion fails, but not click_link.
I've verified that "CSV" does not appear anywhere else in the HTML, not as id, class, title

Any ideas? Going back to Poltergeist for now, but would be quite keen to get headless Chrome working at some point. Not sure where the issue might as tried different versions of Chrome and Chromedriver with exactly same result

**Comment by tomdracz** [comment]
Setting window size seems to get rid of the issue, somehow...

**Comment by twalpole** [comment]
@tomdracz I’m glad changing the window size fixed things for you, although I have no clue why it would. However, I am surprised that your `click_link` test passes reliably. There is no guarantee that any actions triggered by `click_link` have completed when it returns. Because of that you should have an expectation on a visual change, to force a wait, inside the change expect block  

For your other issue you’re probably running into a Chrome/chromedriver bug   https://bugs.chromium.org/p/chromedriver/issues/detail?id=1771&q=sendkeys&sort=-id&colspec=ID%20Status%20Pri%20Owner%20Summary
