### ISSUE TITLE
Should we use PhantomJS with poltergeist driver for a brand new application?

### ISSUE THREAD

**Issue by dkumar431** [teamcapybara/capybara#1913]
I am asking this after going through the following links.

1. https://en.wikipedia.org/wiki/PhantomJS (Wiki says it development status is abandoned)
2. https://groups.google.com/forum/#!msg/phantomjs/9aI5d-LDuNE/5Z3SMZrqAQAJ

I am not sure should i go for 
**Phantomjs with Poltergeist** 
OR 
**Chrome with Selenium** (though its slow but actively maintained) ?

Any thoughts on https://github.com/GoogleChrome/puppeteer ? Can we use it with Rails?

**Comment by twalpole** [comment]
As you have noticed PhatomJS has been abandoned and the last stable release of it (2.1.1) was basically equivalent to a 6 year old browser.  Therefore in order to use Poltergeist with a modern app you need to transpile/polyfill all JS code to be ES5 compatible, and ensure that no modern CSS is actually required for your pages to function correctly.   IMHO you'll probably have fewer issues going with Chrome with Selenium, since it uses current releases of Chrome and therefore supports current JS And CSS completely.  While it is a bit slower than Poltergeist (mainly because it supports more) the fact that Rails 5.1+ no longer requires database_cleaner and can run tests in transactional mode can make up some of that speed.  

As far as puppeteer goes, I have a fork of Poltergeist which I am swapping over to use puppeteer instead of PhantomJS -- hope to have something stable enough to release an alpha later this week.
