### ISSUE TITLE
Unable to fill_in a visible field

### ISSUE THREAD

**Issue by heaven** [teamcapybara/capybara#1914]
## Meta
Capybara Version: 2.15.1
Driver Information (and browser if relevant): tested with chrome, chrome_headless, and poltergeist

Here's the problem:
```
(byebug) find("div#profile_tag_ids-chosen input[type=text]")
#<Capybara::Node::Element tag="input" path="/html/body/div[3]/div/div/div[2]/div/div/div/form/div[1]/div[2]/div/ul/li/input">

(byebug) find("div#profile_tag_ids-chosen input[type=text]").visible?
true

(byebug) find("div#profile_tag_ids-chosen input[type=text]").disabled?
false

(byebug) fill_in("div#profile_tag_ids-chosen input[type=text]", with: "test")
*** Capybara::ElementNotFound Exception: Unable to find visible field "div#profile_tag_ids-chosen input[type=text]" that is not disabled
```
In chrome driver, I can see the input is visible and clickable:
<img width="745" alt="screen shot 2017-09-20 at 14 24 16" src="https://user-images.githubusercontent.com/126732/30641383-81f4a4b2-9e0f-11e7-9a4c-a372b752cedb.png">

**Comment by heaven** [comment]
I think this is something related to `Capybara.default_max_wait_time` and async updates to the page, which Capybara doesn't detect. Weird because this did work previously. Should there be a method to trigger page re-sync?

Because while testing interactive pages everything moves to `evaluate_script` calls:
```
(byebug) page.all("div.chosen-dropdown")
 => []

(byebug) page.evaluate_script("$('div.chosen-dropdown')")
 => [#<Capybara::Node::Element tag="div" path="/html/body/div[2]">]
```

I don't think increasing `default_max_wait_time` and this does not solve the problem anyway and only makes our tests slower.

**Comment by twalpole** [comment]
`fill_in` doesn’t take a CSS selector to locate the Element by, it takes name,id, or label text of a field.
Also increasing `default_max_wait_time` shouldn’t make working tests take any longer than they do currently. It’s the maximum time it will wait before raising an error, if the conditions are immediately met the rest moves on immediately

**Comment by heaven** [comment]
So I just set it to 10 seconds, the test took much longer and failed, screenshot shows the element is on the page, and this is still happening:
```
(byebug) page.all("div.chosen-dropdown")
 => []

(byebug) page.evaluate_script("$('div.chosen-dropdown')")
 => [#<Capybara::Node::Element tag="div" path="/html/body/div[2]">]
```

**Comment by twalpole** [comment]
@heaven Yes - it can make failures take longer - In that case it's waiting the maximum time for the element to become visible on the page, which it never does - hence it takes longer to fail.  

Your `evaluate_script` example, doesn't prove anything since the JQuery code isn't not checking for visibility of elements.  The equivalent to your `evaluate_script` example would be something like `page.find("div.chose-dropdown", visible: false)` since that then wouldn't be verifying visibility. 

As for why it isn't finding the element, I would guess because it's not visible when you run the code.  Your screenshot doesn't actually show the `div.chosen-dropdown` element but I would guess it's not actually visible until you click on the dropdown arrow or fill in some text and an Ajax request returns.  

Note: 'page.all` doesn't wait at all unless you specify one of the count options `page.all("div.chose-dropdown", minimum:1)`

**Comment by twalpole** [comment]
Oh - and I missed one thing in what `fill_in` takes -- it takes name,id, placeholder or label text of a field

**Comment by twalpole** [comment]
So if Capybara is finding it by path then it obviously is detecting changes on the page after the page has been loaded.  I have no clue why it's not detecting it by CSS for you, the only difference I see is that you're calling `find` on the `page` object (current session) whereas your CSS finds are called on the current test object.  Are you overriding `find` in test objects somehow?  Try calling the find on page and see if that makes a difference.  As far as your `wait_until` method, it's completely unnecessary

    wait_until(timeout=15) do
      page.all("div.chosen-dropdown").any?
    end

is equivalent to

    page.all("div.chosen-dropdown", minimum: 1, wait: 15)

or since you're not doing anything with the result

     expect(page).to have_css('div.chosen-dropdown', wait: 15)  # RSpec
     assert_css('div.chosen-dropdown', wait: 15) # minitest

If calling `find` on `page` doesn't make a difference (if it does you're overriding find somehow) then can you provide an example that produces the issue

**Comment by twalpole** [comment]
Here is code showing it working fine on the chosen demo site

    require 'capybara/dsl'
    require 'selenium-webdriver'

    session = Capybara::Session.new(:selenium_chrome)
    session.visit "https://harvesthq.github.io/chosen/"

    container = session.first('div.chosen-container-single').click
    container.find('div.chosen-drop li', text: 'Angola').click
    puts session.first('select.chosen-select', visible: false).value

**Comment by twalpole** [comment]
One thing that just popped into my head -- You're not inside a `within` block that's scoped you away from the element you're trying to find are you????  That wouldn't affect the find by xpath because you're defeating the scoping by not starting your XPath queries with `.` - https://github.com/teamcapybara/capybara#beware-the-xpath--trap

**Comment by heaven** [comment]
Hi, Thank you for the advice, we do need these two `wait` methods because we also do use them often to wait for other events to happen, e.g. to wait before an object appears in Solr search results, so we're used to using it everywhere. But might be really worth using the `wait` option as you suggested, thanks. I didn't know it exists, as well as the `minimum` one.

```
(byebug) page.find(:xpath, "/html/body/div[2]")
#<Capybara::Node::Element tag="div" path="/html/body/div[2]">
(byebug) page.find(:xpath, "/html/body/div[2]")[:class]
"chosen-dropdown single downside opened"
(byebug) page.find(:xpath, "/html/body/div[2]").visible?
true
(byebug) page.find("div.chosen-dropdown")
*** Capybara::ElementNotFound Exception: Unable to find visible css "div.chosen-dropdown"

nil
(byebug) within("body") { page.find("div.chosen-dropdown") }
*** Capybara::ElementNotFound Exception: Unable to find visible css "body"

nil
(byebug) within("html") { page.find("div.chosen-dropdown") }
*** Capybara::ElementNotFound Exception: Unable to find visible css "html"

nil
(byebug) within(:xpath, "/html/body") { page.find("div.chosen-dropdown") }
#<Capybara::Node::Element tag="div" path="/html/body/div[2]">
(byebug)
```

It seems you're right about the `within` block:
```
(byebug) page.send :scopes
[nil, #<Capybara::Node::Element tag="form" path="/html/body/div[1]/div[2]/div[3]/div/div[2]/div/form">]
```

Thank you for the help, now I only have to find where we entered that scope.

**Comment by twalpole** [comment]
@heaven So it sounds like chosen is dynamically adding the dropdown box to the end of the document and then positioning it absolutely on the page.  If that's the case then the fact that you're inside a `within` for scoping the initial element isn't a problem you just have to break out of the scope inside your helper function.  You can either do that with `document` or by using xpath queries and intentionally not starting with `.//` so as to ignore the current scope.  So your helper method would become something along the lines of

    def chosen_select(id, *values)
       # find initial element in the current scope and click it to trigger the dropdown
       page.find("div##{id}-chosen input[type=text]").click 
       # escape from the current scope and find the newly visible dropdown element
       dropdown = page.document.find('div.chosen-dropdown')
        # dropdown = page.find(:xpath, "//div[contains(concat(' ', normalize-space(@class), ' '), ' chosen-dropdown ')]"   # XPath equivalent, no starting "." so breaks out of scope
       values.each do |val|
          dropdown.find('li', text: val).click
       end
    end

As for the `wait` option, its value defaults to `Capybara.default_max_wait_time`. So as long as you specify `Capybara.default_max_wait_time` to a reasonable time for your app  you should only need to specify it in calls to find, etc where you need a longer timeout than would be normal for your general app behavior or, more commonly, when you want to shorten it to make an immediate decision based on the presence/absence of an element.  

    if page.has_text?("blah", wait: 0)  # don't wait any time for the text to appear just do something different based on it being there or not

Specifying `default_max_wait_time` (or the `wait` option)  as a little longer than expected also won't make your tests runs slower (assuming they all succeed) since they are maximum amounts of time to wait not a fixed wait period.

**Comment by heaven** [comment]
Hi, thanks for the explanation, I think it might be worth to add a more detailed information about the available options to the readme because I wasn't aware of `wait` and `minimum` options.

Here's the version of the helper I ended up with:
```ruby
def chosen_select(id, *values)
  element = find("select##{id}", :visible => false)
  return false unless element

  # Exit all user scopes
  within(:xpath, "/html/body") do
    values.each do |value|
      find("div##{id}-chosen input[type=text]").set(value)

      # wait for AJAX request to finish
      expect(page).to have_no_css("div##{id}-chosen.loading", wait: 10)

      # wait for dropdown to show up and click
      find("div.chosen-dropdown li", text: value, wait: 10).click
    end
  end
end
```

**Comment by twalpole** [comment]
@heaven Ok - that looks like it will work, other than the `return false unless element` - `find` returns an element or raises an exception - so it will never return `null` so your method will never return false.
