### ISSUE TITLE
Capybara 2.15.2 breaks when visting '/' if app_host is set with a trailing '/'

### ISSUE THREAD

**Issue by twalpole** [teamcapybara/capybara#1918]
Title says it all

**Comment by twalpole** [comment]
Fixed via a5f81f97b66559ef20083b16050a364b1036a517

**Comment by twalpole** [comment]
Fixed in 2.15.3

**Comment by jodigiordano** [comment]
I switched from `2.15.1` to `2.15.2` and all my tests fail because the test server is not spawned (maybe because of an internal error?). I _think_ its related to this issue.

My tests fail with and without setting `app_host`.
When I set `app_host`, I do not put a trailing `/`.

I also tried `2.15.3` without luck.

Let me know if you need more information.

**Comment by twalpole** [comment]
@jodigiordano Yes more info would be needed.  What are your settings? What makes you say the test server is not spawned? What error do you get?  Potentially a way to replicate the issue.  I don't see how this issue would in any way prevent the test server from starting up.

**Comment by jodigiordano** [comment]
Ah man, sorry for the false positive, I tried to come up with some minimal code to replicate the issue and I realized the error is happening in a monkey patch of `visit` in our project.

**Comment by twalpole** [comment]
@jodigiordano No problem, do you mind telling me why you needed to monkey patch `visit`  (just wondering if there's some extra flexibility generally needed in it)

**Comment by BrianHawley** [comment]
Made an issue for the problems caused by this fix.
