### ISSUE TITLE
drag_to unexpected behavior

### ISSUE THREAD

**Issue by rjchaveiro** [teamcapybara/capybara#1924]
## Meta
Capybara Version:
2.10.1
Driver Information (and browser if relevant):
Poltergeist driver with PhantonJS

## Expected Behavior
To drag a div from one table to the other.
## Actual Behavior
Div doesn't get dragged at all. Given a nested element.
## Steps to reproduce

Whenever there's an element or text nested inside a dynamically created button inside of a form, the element does not get dragged, causing the test to fail.

The `.ejs` html that generates the tag
```EJS
   <% if (view.isSearchResult) { %>
      <button type="button" class="btn btn-default locate-btn locate">
          <i class="mi md-gps-fixed md-14" alt="gps_fixed"></i>`
      </button>
    <% } %>
```
 and the test
```Ruby
 it 'drags the story to other columns', js: true do
      page.execute_script("$('#form_search').submit()")
      
      resultStory = find('.searchResult')
      target = page.first('#chilly_bin')      
      resultStory.drag_to(target)

      expect(page).to_not have_css('.searchResult')
      expect(find('#chilly_bin')).to have_content('Search for me')
    end
```
Available in this commit.
Codeminer42/cm42-central@7cc2a6f80857bee506a231b477ef7631960f8d87

**Comment by twalpole** [comment]
@What events are you depending on to detect drag and drop?

**Comment by twalpole** [comment]
So I spent a few minutes trying to get the specific test to run, and am giving up -- not sure if I need to register a cloud account somewhere or what, but enough time wasted.  Anyway, I'm going to close this because whatever is causing this is going to be Poltergeist or PhantomJS since all Capybara does is tell the driver to drag, everything else is handled by the driver.  I would suggest upgrading to the latest poltergeist and capybara, and if that doesn't fix your issue report it on Poltergeist with enough details for someone to either run the exact test, or (better) a small self contained example that shows the issue.
