### ISSUE TITLE
Capybara::Node::Element#disabled? returns incorrect value

### ISSUE THREAD

**Issue by moveson** [teamcapybara/capybara#1925]
**Note:** This is for issues with Capybara.  If you have a howto type question, please ask on the mailing list as requested in the README: http://groups.google.com/group/ruby-capybara

## Meta
Capybara Version:
2.15.4
Driver Information (and browser if relevant):
selenium-chromedriver 2.33.506106 (8a06c39c4582fbfbab6966dbb1c38a9173bfb1a2)
with Chrome 61.0.3163.100 (Official Build) (64-bit)

## Expected Behavior
when `element[:disabled] == "true"`
`element.disabled?` should return `true`

## Actual Behavior
`element.disabled?` returns `false`

## Steps to reproduce

```
[1] pry(#<RSpec::ExampleGroups::EventStagingAppFlow>)> continue_button.inspect
=> "#<Capybara::Node::Element tag=\"a\" path=\"/html/body/div[2]/div[2]/div/div/article/div[8]/div/a\">"
[2] pry(#<RSpec::ExampleGroups::EventStagingAppFlow>)> continue_button[:disabled]
=> "true"
[3] pry(#<RSpec::ExampleGroups::EventStagingAppFlow>)> continue_button.disabled?
=> false
```

**Comment by twalpole** [comment]
This is behaving as expected. `disabled` is an invalid attribute for `<a>` elements and therefore has no effect on the element. Hence the link is not actually disabled and `disabled?` correctly returns false

**Comment by moveson** [comment]
All buttons are `<a>` elements, correct? The button in question is indeed greyed out when `[:disabled]` is `"true"` and is not greyed out when `[:disabled]` is missing. What is the correct way to check if a button is disabled?

**Comment by twalpole** [comment]
@moveson No - buttons could be `<button>` elements, they could be `<input type="submit">` elements, etc.  `<a>` elements are links (if they have an `href` attribute) and link placeholders if they don't have an `href` attribute.  Links may be styled to look like buttons, but they would still be links.  If whatever framework/css you're using is styling links to look like buttons and then styling them as greyed out when they have a `disabled` attribute on them, I would guess it's also catching the click on the link via JS in order to implement the disabling (although if JS is required that then raises the question of why not just use actual button elements that support `disabled`). That would be custom behavior, unrelated to HTMLs concept of disabled, and therefore your check would need to be custom too -- That might be as simple as `element[:disabled]` or may require `execute_script(...)`  depending on exactly what your framework is doing. 

Here is the HTML spec on the disabled attribute - https://www.w3.org/TR/html51/disabled-elements.html#disabled-elements

**Comment by moveson** [comment]
The project is built in Rails 5. Buttons are generated with Rails `link_to` helpers, which create `<a>` elements. Virtually every button in the project is an `<a>` element. Capybara recognizes the buttons as such; for example, I can use `click_button` to click these elements. 

I can (and have) implemented a check on `element[:disabled]`, but that's a clunky solution. I think it makes sense for `#disabled?` to check for a `[:disabled]` attribute on `<a>` elements and return `true` if the attribute is `"true"`. Is there an argument against doing so?

**Comment by twalpole** [comment]
@moveson Yes -- because `disabled` is not a valid attribute for `<a>` elements. Create an HTML page with an `<a disabled="disabled" href="some_link">my link</a>` element on it, and then click on it -- the click will still happen - HTML has no concept of disabled links. 

Additionally, there is no way `click_button` clicks on an `<a>` element UNLESS you have overwritten `click_button` or the Capybara `:button` selector in your project.  https://github.com/teamcapybara/capybara/blob/master/lib/capybara/selector.rb#L183 is where the :button selector (used to find the buttons `click_button` will click) is implemented and as you can see - it only finds `<button>` and `<input>` elements - not `<a>`

**Comment by moveson** [comment]
Yes, I see that now. The buttons I am accessing with `click_button` are in fact `<button>` elements. My mistake. OK, I understand the reasoning and will proceed by either checking the `[:disabled]` attribute manually or converting `<a>` tags to `<button>` tags.

**Comment by twalpole** [comment]
Another option for you would be to define your own custom selector type along the lines of 

    Capybara.add_selector(:custom_button) do
      label "our apps custom buttons"
      xpath do |locator|
         XPath.descendant(:a)[XPath.string.n.is(locator)]  # implement any other searching forms wanted
      end
      filter(:disabled, :boolean, default: false, skip_if: :all) { |node, value| not(value ^ node[:disabled]=="true") }
       ... # any other filters needed and description
    end

then define a method like

    def click_custom_button(locator)
      find(:custom_button, locator).click
    end

which won't let you actually call 'disabled?' on it but will let you do things like

    expect(page).to have_selector(:custom_button, "My button text", disabled: true)

to check for a disabled button on the page, which is far better than `expect(element.disabled?).to be true` since it would utilize waiting/retrying.
