### ISSUE TITLE
Unable to find link or button with click_on using the value attribute of a link

### ISSUE THREAD

**Issue by zedtux** [teamcapybara/capybara#1928]
## Meta
Capybara Version:
2.14.4

Driver Information (and browser if relevant):
Poltergeist

## Expected Behavior

Capybara to click a link by its value.

## Actual Behavior

[The capybara `click_on` documentation](https://github.com/teamcapybara/capybara/blob/2.14.4/lib/capybara/node/actions.rb#L8) is stating that it can find a link or button by its text, id or value but I have the error `Unable to find link or button "Comfort"` when trying to click it.

Here is html of the link I'm trying to click on:
```html
<a class="btn btn-primary" value="Comfort" href="/comfort">subscribe</a>
```

I did try using the `id` field instead of `value`, and it is working.

## Steps to reproduce

The capybara code is something like this (I have method to generate the parameter given to `click_on`):

```ruby
click_on('Comfort')
```

And the HTML is already described in the *Actual Behavior* section.

There is no hiding on the link, I can see it on the screenshot.

**Comment by twalpole** [comment]
`click_on` is an alias for `click_link_or_button`, so it will click links or buttons (button elements and 'submit', 'reset', 'image', 'button' type input elements.  Because of that it matches on a few things, however since `value` is not a valid attribute for an `<a>` element it doesn't match on value for links.  So, while the documentation needs to be clarified, the behavior is correct.

**Comment by zedtux** [comment]
> the documentation needs to be clarified

I agree with you. So why closing this issue as there is an action to be taken?

**Comment by twalpole** [comment]
@zedtux I closed it and created a new issue specifically about the documentation.

**Comment by zedtux** [comment]
Cool, thank you @twalpole.
