### ISSUE TITLE
Capybara "accept_alert" does not work for headless chrome

### ISSUE THREAD

**Issue by pachonk** [teamcapybara/capybara#1946]
## Meta
Capybara Version:
2.16.1
Driver Information (and browser if relevant):
Headless Chrome:
```
# frozen_string_literal: true

Capybara.register_driver :headless_chrome do |app|
  capabilities = Selenium::WebDriver::Remote::Capabilities.chrome(
    chromeOptions: { args: %w[headless disable-gpu] }
  )

  Capybara::Selenium::Driver.new app,
                                 browser: :chrome,
                                 desired_capabilities: capabilities
end
```

## Expected Behavior
`page.accept_alert` to accept an expected alert box

## Actual Behavior
```
     ArgumentError:
       Block that triggers the system modal is missing
```

## Other Notes

This only happens when chrome is in headless, if I remove the headless arg, it works fine.

**Comment by twalpole** [comment]
This is as expected.  Every Capybara driver (other than selenium in non-headless mode) requires to be passed a block which contains the actions that trigger the system modal to appear.  This is because the drivers need prior knowledge that the modal will be triggered.  Selenium in non-headless currently supports a mode which doesn't require the block but probably won't when 3.0 releases and you really should be passing the block as documented - https://github.com/teamcapybara/capybara#modals

**Comment by pachonk** [comment]
Hey, thanks Thomas.
I was looking all over and I couldn't figure out this difference. That
makes sense.

**Comment by twalpole** [comment]
@pachonk You're welcome.  The non-headless mode works correctly with the block passing too, so you should just be using that form at all times.
