### ISSUE TITLE
Script tag causing contradictory expectations to both pass

### ISSUE THREAD

**Issue by dxypher** [teamcapybara/capybara#1976]
# New Document## Meta
Capybara Version:

	capybara (2.18.0)
Driver Information:

	poltergeist (1.17.0)

## Expected Behavior
I have a simple HTML page whose contents I want to test
The page has this text "Example Header"

**should pass**

```
expect(page).to have_content "Example Header"
```

**should fail**

```
expect(page).not_to have_content "Example Header"
```

## Actual Behavior
Both expectations pass

Looking at the test logs it looks like ``` location.reload(); ``` is being run.
If I delete the script tag and its contents the tests behave as expected

## Steps to reproduce
```
<div class="container-fluid">
  <div class="row justify-content-center" id="main-page-header">
    <div class="col-md-8 text-center">
      <h2 class="display-4">Example Header</h2>
    </div>
  </div>
</div>
<script>
  
  // This script is added for dealing with going back to a previously page which was loaded with Ajax

  $(window).bind("popstate", function() {
    location.reload();
  });

</script>

```

**Comment by twalpole** [comment]
I'm unclear as to what you think the issue with Capybara is doing here.  Both of those expectations when run will wait/retry until their condition passes (or Capybara.default_max_wait_time seconds expires), so if when you start running each of them the text was missing from the page (page not loaded yet, etc) and then the text shows up the page both would pass, just one would wait a little longer to pass.  Without more context around exactly how and when you are running those expectations it seems like it's probably working as designed.
 
The closest case to where one would definitely pass while one would fail would be to do

    expect(page).to have_content("Example Header", wait: false)

vs 

    expect(page).not_to have_content("Example Header", wait: false)

**Comment by dxypher** [comment]
@twalpole 
I'm not sure why the window popstate event is being triggered when running the spec. Its possible this is not Capybara but something with poltergeist.

Also I'm not understanding... if Capybara waits and retries until the expectations pass why would ``` expect(page).to have_content "Example Header" ``` fail?

Also, what value does **not_to have_content** have if it doesn't wait for the page to be loaded before checking if content is present? ( maybe I'm just misunderstanding )

Thanks for the feedback.

**Comment by twalpole** [comment]
@dxypher I have no idea why (or even if) the popstate event is being triggered.  It could be something poltergeist is doing (more likely phantoms) or it could be something different.  Have you tried running with a different driver (selenium perhaps) to see if it is limited to a specific driver?  It's impossible for me to say because you've provided an HTML fragment and one/two lines of your test completely out of context, that's not enough to have any clue what's happening or recreate and test the issue.  The one thing I can say for sure is that Capybara itself isn't firing the popstate event.

-  Also I'm not understanding... if Capybara waits and retries until the expectations pass why would expect(page).to have_content "Example Header" fail?

You left off the "or Capybara.default_max_wait_time seconds expires"  which would be when/how they would/could fail

- Also, what value does not_to have_content have if it doesn't wait for the page to be loaded before checking if content is present? ( maybe I'm just misunderstanding )

Nothing in Capybara guarantees to wait for a page to be loaded (some drivers try to for some actions but can't guarantee it either) because the definition of "loaded" is not uniform.  Does "loaded" mean when the initial html has loaded, does it mean when resources have loaded, does it mean when the Ajax triggered by the initial resources to load info for the rest of the page has completed, etc, etc.  That is why the assertions/matchers have waiting/retrying behavior.  As to `not_to` specifically the requirements are never strictly "the page won't have the text 'widget a'" there's always an applied requirement like "the page won't have the text 'widget a' (when it's displaying widgets)".  Therefore usage would be

    expect(page).to have_text('Widgets')
    expect(page).not_to have_text('widget a')

or

    expect(page).to have_text('Widgets').and have_no_text('widget a)

where the first expectation ensures the page is in the expected state to check that specific text is not included.  Another use is where you have a button that removes text from the page via JS

    expect(page).to have_text('Something')
    click_button 'remove something'
    expect(page).not_to have_text('Something')

**Comment by dxypher** [comment]
@twalpole Thanks for the info...you're right this is an issue with phantomjs.

For anyone who might be having the same problem here was a solution I found:
https://github.com/decidim/decidim/pull/1458

```
  $(window).bind("popstate", function(e) {
    if(e.isTrusted) {
       location.reload();
    }
  });
```

**Comment by dxypher** [comment]
@twalpole Thanks for the info, the issue was with phantomjs as you suggested.

For anyone who may also face this problem heres a solution I found:
https://github.com/decidim/decidim/pull/1458

```
```
