### ISSUE TITLE
visit('link#with_anchor') raises ERROR Net::ReadTimeout: Net::ReadTimeout

### ISSUE THREAD

**Issue by dwt** [teamcapybara/capybara#1978]
## Meta
Capybara Version: 2.18.0
Driver Information (and browser if relevant):
selenium-webdriver 3.9.0 with Chome 64.0.3282.186

## Expected Behavior
visit('link#target') should just work

## Actual Behavior
it doesn't

```
[2018-02-28 08:35:52] ERROR Net::ReadTimeout: Net::ReadTimeout
	/Users/dwt/Library/Homebrew/Cellar/ruby/2.4.2_1/lib/ruby/2.4.0/net/protocol.rb:176:in `rbuf_fill'
```

## Steps to reproduce
https://gist.github.com/dwt/a8caf3a68086fd9651fcbfa00442bf60

**Comment by twalpole** [comment]
That gist runs fine for me - More of the stack trace may let me see something it's not reproducible with the code provided.

**Comment by twalpole** [comment]
FYI - the output I get when running is

```
ruby visit_with_anchor.rb
== Sinatra (v2.0.1) has taken the stage on 8080 for development with backup from Puma
Puma starting in single mode...
* Version 3.11.2 (ruby 2.5.0-p0), codename: Love Song
* Min threads: 0, max threads: 16
* Environment: development
* Listening on tcp://localhost:8080
Use Ctrl-C to stop
before visit without anchor
::1 - - [28/Feb/2018:00:56:18 -0800] "GET / HTTP/1.1" 200 47 0.0409
before visit with anchor
::1 - - [28/Feb/2018:00:56:19 -0800] "GET /favicon.ico HTTP/1.1" 404 469 0.0010
the print after this visit is not reached, instead it hangs and then shows an
ERROR Net::ReadTimeout: Net::ReadTimeout - just wait for it
after visit with anchor
^C- Gracefully stopping, waiting for requests to finish
=== puma shutdown: 2018-02-28 00:56:22 -0800 ===
- Goodbye!
== Sinatra has ended his set (crowd applauds)
```
I did remove CHROMEDRIVER_PATH and CHROME_PATH because they make no sense in my setup where they're already in the PATH

**Comment by rbu** [comment]
I can also reproduce this on Linux x86_64 with the following versions:
* chromedriver: 2.33 and 2.35
* Chrome 63.0.3239.108, 64.0.3282.167

I cannot reproduce this with:
* chromedriver: 2.35
* Chrome: 65.0.3325.88 and 66.0.3355.0

**Comment by dwt** [comment]
Am I missing a page that tells me which browser versions are required to work with Capybara?

Needing to use beta versions of Chrome for full functionality seems like something that should be mentioned somewhere?

**Comment by twalpole** [comment]
@dwt Capybara is an API level above the individual drivers.  Since you're using the selenium driver with Chrome that means the lower levels are `selenium-webdriver` -> `chromedriver` -> `chrome`.  `chromedriver` is very dependent on the version of Chrome it's being used with, and those are disclosed on the chromedriver download sites.  Our test suite is run on travis daily with the latest chromedriver and latest chrome (stable) and is currently passing (it does not have any tests that navigate to a target). If there are errors causing timeouts in the lower levels it's not always possible for us to work around them since they are in code we don't control (a full stacktrace would show that) and especially not when we don't even know there is an issue.  Maybe you're running into - https://bugs.chromium.org/p/chromedriver/issues/detail?id=2025&can=1&q=timeout&colspec=ID%20Status%20Pri%20Owner%20Summary

**Comment by twalpole** [comment]
@rbu Thanks - I'll have to check later what version of Chrome it was running against when I tried.

**Comment by twalpole** [comment]
Ok -- when I ran it last night it turns out I had Chrome 65 beta on my machine.  I have now reproduced this and it is the Chrome/chromedriver issue mentioned in the previously linked issue. 

 It's not specifically doing `visit('link#with_anchor')` that causes the issue, it is doing that after doing `visit('link')` without performing any other actions that would change the current url. 

This is a Chrome/chromedriver issue and there is nothing Capybara can really do about it.  however I am adding a test to the Capybara test suite which will only be skipped for chrome <= 64 to track the issue.  I would prefer to mark it pending however the bug leaves chromedriver in a state that affects other tests.
