### ISSUE TITLE
Iframe loading Issue - Not able to find Element

### ISSUE THREAD

**Issue by GithubUserAA** [teamcapybara/capybara#2007]
Capybara Version: 2.17
Ruby -1.9.3
Driver Information (and browser if relevant):
Capybara.default_driver = :poltergeist

## Expected Behavior
When a 'Add Server' button is clicked - should navigate to next page to enter more server details
## Actual Behavior
Navigating to the intermediate page (iframe content is not loaded and blank page is displayed)
and its trying to find the element in that frame

## Steps to reproduce
**cucumber steps**
And I click on the "Add Server" button
And I sleep for "15"
And I set "ABCD" for "Server Name" in "Reference"

within_frame 'g_main' do
page.should have_content('Server Name')
puts page.all(:xpath, ".//*[@id='label.server_name']").length
if(page.has_xpath?(".//*[@id='label.server_name']"))
 find(:xpath,".//input[@id='sys_display.server_name']").native.send_key 'ABCD'
else
  puts ' Server Name field value not Set to ABCD'
end
 
 I am not having issue with xpath but only beacuse a blank iFrame page loading was in process after the click operation  the script is trying to find the element in that page and failing everytime.Iframe completes loading in 5 sec - inspite of giving the 'sleep 30' it is still searching the element in the iframe which is not loaded completely.

**Comment by twalpole** [comment]
What exactly is the issue you're having here?  If it's that a page isn't loading then it's possible you are experiencing a bug (or limitation due to your page using unsupported features) in Poltergeist.   Then again it could be something as simple as your app loading mobile pages because the screen size is set too small.   With the provided info there is no way to tell, and nothing we can do, let alone confirm it's an actual issue with Capybara or just user error.

Your `Expected Behavior` talks about going from the original page to the next and filling in a box, but then your `Actual Behavior` talks about an intermediate page.  Your sample code changes into an iframe, but we have no idea where that is supposed to be????  You also mention a `sleep 30` but your test shows `15`  and then you say the iframe loads in 5 seconds which I not sure the relevance of.  None of it is consistent.  That combined with the fact you haven't provided a way for us to replicate any of this means this is completely non-actionable.

**Comment by twalpole** [comment]
If you provide a way to replicate the issue you are seeing we will reopen this and look at it.

**Comment by GithubUserAA** [comment]
Sir, sorry to say but i can't provide a way to replicate the issue as i work on secured applications.I am attaching the word document which will help you explain my scenario.
[Issuescreenshots.docx](https://github.com/teamcapybara/capybara/files/1897898/Issuescreenshots.docx)

**Comment by twalpole** [comment]
Just because you work on "secured applications" doesn't mean you can't provide an example that replicates the issue.  Additionally Your docx really doesn't clarify anything since now it's talking about multiple windows (before it was frames in the same window).  In summary, without you producing an example that allows us to replicate the issue there's nothing we can do.

**Comment by GithubUserAA** [comment]
Yeh i was able to resolve it - it needed a refresh of that page so that it loads completely - but refresh command also didn't worked for me so i have to revisit the current Url by capturing it.
 **visit** "Url Name"
It's the synchronization problem - so i thought you'll give me some workarounds to try as i am new to cabybara and all the issues may not be replicated.
