### ISSUE TITLE
reset_sessions isnt working with Google OAuth

### ISSUE THREAD

**Issue by jlinville01** [teamcapybara/capybara#2008]
## Meta
Capybara Version:
2.18.0
Driver Information (and browser if relevant):
selenium-webdriver 3.8.0 with Chrome 65

## Expected Behavior
User arrives at clean-session Google OAuth login page.

## Actual Behavior
User never accesses Google OAuth page because the session wasn't reset and user is already logged in. To clarify, our website session is being reset but not Google OAuths.

## Steps to reproduce
My app requires users to login via Google OAuth. When I run multiple tests Google OAuth is not resetting the session, so after the first test all following tests access our site and are already logged in.

I discovered this issue fairly recently and have run into 3 scenarios (I've included basic examples). Each scenario starts by having the user navigate to our login page, click a button that sends user to Google OAuth, logs in and then verifies the url.

The **first scenario** is just navigating to our site and logging in. The result of this is that the first test passes, but all following tests are expecting to arrive at the Google OAuth login page but are already logged in:

	feature 'All Films Page' do
	  context 'user is logged in as an Admin role' do
	    before(:each) do
	      Capybara.reset_sessions!

	      visit('/')
	      app.google_signin.sign_into_app('admin')
	    end

	    scenario '1' do
	      expect(page).to have_current_path('/films')
	    end

	    scenario '2' do
	      expect(page).to have_current_path('/films')
	    end
	  end
	end

The **second scenario** adds a 'reset_sessions!' for Google OAuth. The result of this is that after the first test, the user arrives at Google OAuth but the previous user is a selectable option as previously logged in.

	feature 'All Films Page' do
	  context 'user is logged in as an Admin role' do
	    before(:each) do
	      visit('https://accounts.google.com')
	      Capybara.reset_sessions!
	      visit('/')

	      app.google_signin.sign_into_app('admin')
	    end

	    scenario '1', :integration do
	      expect(page).to have_current_path('/films')
	    end

	    scenario '2', :integration do
	      expect(page).to have_current_path('/films')
	    end
	  end
	end

The **third scenario** adds two 'reset_sessions!' for Google OAuth. This creates the intended result of each test having its session reset.

	feature 'All Films Page' do
	  context 'user is logged in as an Admin role' do
	    before(:each) do
	      visit('https://accounts.google.com')
	      Capybara.reset_sessions!
	      visit('/')

	      visit('https://accounts.google.com')
	      Capybara.reset_sessions!
	      visit('/')

	      app.google_signin.sign_into_app('admin')
	    end

	    scenario '1', :integration do
	      expect(page).to have_current_path('/films')
	    end

	    scenario '2', :integration do
	      expect(page).to have_current_path('/films')
	    end
	  end
	end

**Comment by twalpole** [comment]
I answered this on your StackOverflow post, however basically it's behaving as designed.  Due to a limitation (some might say deficiency) in the WebDriver spec - https://www.w3.org/TR/webdriver/#delete-all-cookies - only cookies for the current documents domain may be deleted.  This means if you're tests are storing cookies in domains other than the one your test ends on you will need to manually handle removing them.  Since Capybara has know way of knowing all the domains your app ends up visiting there's really no way for Capybara to automate it, and any overhead incurred trying to do it would be too much for the limited amount of times this occurs.  The real issue here is that you are actually logging into live Google, rather than putting your oauth library into a test mode, which is generally not necessary nor encouraged when running tests.

**Comment by lsmolic** [comment]
Thanks @twalpole ! We appreciate the feedback.

**Comment by jlinville01** [comment]
@twalpole Thank you for reaching out! I left a question for your stackoverflow answer
