### ISSUE TITLE
The .disabled? method does not work correctly on non-disabled fieldsets

### ISSUE THREAD

**Issue by Jack12816** [teamcapybara/capybara#2062]
The return type of the `.disabled?` method is mixed. It returns boolean (`true`) in case the element has the disabled attribute and `nil` when the disabled attribute is not present.

## Meta
Capybara Version: 3.3.1

Driver Information (and browser if relevant): selenium-webdriver 3.10.0 and Chrome Headless 67.0.3396.87

## Expected Behavior
```ruby
find('fieldset')[:disabled]
# => nil
find('fieldset').disabled?
# => false

find('fieldset')[:disabled]
# => true
find('fieldset').disabled?
# => true
```

## Actual Behavior
```ruby
find('fieldset')[:disabled]
# => nil
find('fieldset').disabled?
# => nil

find('fieldset')[:disabled]
# => true
find('fieldset').disabled?
# => true
```

## Additional information
https://github.com/teamcapybara/capybara/issues/1925#issuecomment-336933569
https://www.w3.org/TR/html51/disabled-elements.html#disabled-elements
https://github.com/teamcapybara/capybara/issues/2059
https://www.rubydoc.info/github/jnicklas/capybara/Capybara%2FNode%2FElement%3Adisabled%3F

**Comment by twalpole** [comment]
This is already fixed in master, but since nil is falsey it's not worth doing a 3.3.2 release for.

**Comment by Jack12816** [comment]
Great, then I'm fine with it. Thank you. I will wait for it with the next regular release. :)

**Comment by twalpole** [comment]
@Jack12816 Just a quick question - What sort of code were you writing that this even came up as an issue?

**Comment by Jack12816** [comment]
The use case is a collapsed form/fieldset which is locked in some circumstances. The gherkin step is to check if the form is locked (disabled) or not.

```ruby
  step 'I see the marketing section is locked' do
    expect(find('#marketing fieldset', visible: :all).disabled?).to be(true)
  end     
```

I didn't find another way to check this better. `have_selector` has no `disabled` flag/filter and there is [no direct rspec matcher for fieldsets](https://www.rubydoc.info/github/jnicklas/capybara/master/Capybara/RSpecMatchers) like for fields or selects etc.

It looks quite odd to me, but maybe you have a better idea how to test this?
But it does not matter for the issues at all. :)

**Comment by twalpole** [comment]
@Jack12816 There is actually a selector type for fieldsets - https://github.com/teamcapybara/capybara/blob/master/lib/capybara/selector.rb#L70 - and in master it has a `disabled` filter (not in 3.3.x though).  So using master you could write something along the lines of 

    expect(find('#marketing')).to have_selector(:fieldset, disabled: true, visible: :all)

In released versions you could use `modify_selector` to add the disabled filter to the existing `:fieldset` selector or you could register your own selector type, or you could just provide a node filter to the query with something like

   expect(find('#marketing')).to have_selector('fieldset', visible: :all){ |node| node.disabled? }

which will remove the race condition your code has by using Capybaras waiting behavior.  Although I'm not really sure what point there is in checking `visible: :all` there since if it's supposed to be not visible it doesn't really matter whether it's disabled so just check for visibility, and if it is supposed to be visible then just check for disabled.  (Specifying `visible: :all` is generally a bad smell because it implies you don't know whether it should or should not be visible which means your test isn't deterministic)

**Comment by twalpole** [comment]
@Jack12816 One side note 

    expect(find('#marketing fieldset', visible: :all).disabled?).to be(true)

you would have been better off using RSpecs built-in predicate matcher

   expect(find('#marketing fieldset', visible: :all)).to be_disabled

however that still has a race condition and overall you'll be better off using any of the Capybara provided matchers in my previous answer.

**Comment by Jack12816** [comment]
> Although I'm not really sure what point there is in checking visible: :all there since if it's supposed to be not visible it doesn't really matter whether it's disabled so just check for visibility, and if it is supposed to be visible then just check for disabled. (Specifying visible: :all is generally a bad smell because it implies you don't know whether it should or should not be visible which means your test isn't deterministic)

Its a collapse which includes the form. Its opened under circumstances by default or it is closed, so I do not care about it's visibility here. 

> expect(find('#marketing')).to have_selector(:fieldset, disabled: true, visible: :all)

Sounds great. I'll wait for this to be released and switch to it then. Thats actually my favorite way of doing this and I was confused that the disabled filter is not yet present. :) (Was also my first approach)

> which will remove the race condition your code has by using Capybaras waiting behavior.

I'am aware of the race condition here. But it's fine, because when the element is available, it has the disabled attribute set or not. This is not dynamic in the sense of waiting for the state change on the DOM.

Thank you for your feedback and the extra mile on helping me out! :)
