### ISSUE TITLE
Targeting elements

### ISSUE THREAD

**Issue by x-yuri** [teamcapybara/capybara#2082]
It's not a howto, but rather "is the API really good" type of question.

I understand you're trying to make it more readable. But doesn't it make it harder to use?

Meaning, different methods have different ways to specify target elements. `find` takes `selector` and `locator`, or just `selector` (defaults to `:css` selector). `check` optionally takes `locator` for `:checkbox` selector. Also, you can specify `id`, `name`, `class`, `option` in the options. I occasionally find myself looking in the [source][1] to find out what the options are exactly. Is there any consistent policy regarding ways to specify a target element?

[1]: https://github.com/teamcapybara/capybara/blob/3.5.1/lib/capybara/selector.rb

Also, it's hard to create helpers on top of it. Today I needed a helper, that checks a checkbox and waits for it to change state. Since it changes state after AJAX request to the server has finished. Also, in one place I can target elements by name (for that I created a `:name` selector), but in others I have to resort to label text (no easy way to assign class to the input itself, `react-bootstrap/lib/Checkbox`). I could have used CSS selector, but `check` doesn't take that sort of thing. So, that resulted in:

```rb
    def check_ajax selector, locator = nil
      Timeout.timeout(Capybara.default_max_wait_time) do
        if locator.nil?
          # here I hardcode what selector `check` uses
          # might change in the future versions
          selector, locator = :checkbox, selector
          check locator
        else
          check Hash[selector, locator]   # in this case it's not a selector,
                                          # but option name
        # it's not clear if I should validate arguments here
        # since it's now supposed to handle just two cases: `locator`, or `:name`, `locator`
        end
        el = find selector, locator
        while ! el.checked?
          sleep 0.05
        end
      end
    end
```

Or I could make it always accept two arguments, with the first taking either `:checkbox`, or `:name`. But I'd still have to rely on `check` using `:checkbox` selector. And supporting even more selectors (if need be) would make it even more complex.

In yet another place I had to assert that checkbox is checked using a CSS class. It would be awesome if I'd be able to do `find(...).check`. That would reduce the helper to:

```rb
def check_ajax el
  Timeout.timeout(Capybara.default_max_wait_time) do
    el.check
    while ! el.checked?
      sleep 0.05
    end
  end
end
```

That would also give users control over which selector to use. Then one could store CSS class in a variable, and use it across the test suite (single source of truth). And not to be let down by `check` taking CSS class, but not CSS selector.

**Comment by twalpole** [comment]
As stated in the issue template - this is for actual issues with Capybara - it is not for philosophical discussion about how you don't like the current API.  If you wish to have that discussion please take it to the mailing list as requested.

That being said I am going to comment on your code because it has at least one very serious issue.  You should NEVER use `Timeout.timeout` (with very very very few exceptions).  It is the most dangerous method in Ruby and will lead to all sorts of flaky errors and crashes.  If you don't understand why do a search. Plenty of people have written blog posts about it.

"Is there any consistent policy regarding ways to specify a target element?" - yes - the built-in selector types take the generally relevant attribute values for those specific element types as the locator- for field elements that would be `id`, `name`, `label text` - and as of a recent release any attribute you specify as your `test_id` attribute.   They also support not passing any locator for the case where the user has scoped to the point where there is only once checkbox, radio button, etc within the current scope. `find` is the generic method that lets you locate any element type depending on which selector type you choose.

"I have to resort to label text" - I would argue you should be using label text a lot more since it checks something visible to the user on the page and is actually relevant to the field you're interacting with.

"I'd still have to rely on check using :checkbox selector" - No you don't, you can use any method you want to find an element - you just can't check it with the `check` method.  You can however call `click` on it, or call `set(true)` depending on exactly what you're trying to do - so your helper could be written today as 

    def check_ajax el
      el.set(true)
      el.assert_matches_selector(:checkbox, checked: true)
      # if using RSpec the previous line would be
      # expect(el).to match_selector(:checkbox, checked: true)
    end

That assumes the element is actually a checkbox so it will match the :checkbox selector - if it wasn't actually a checkbox element but you still want to check `checked?` for some reason then you could use whatever selector type you like and a filter block 

    expect(el).to match_selector(:css, 'whatever') { |node| node.checked? }

Finally if none of those methods meet your needs you can always add/modify your own selector types via `Capybara.add_selector` and `Capybara.modify_selector`

Beyond that, if you believe the docs aren't actually providing the details about what each method accepts as its parameters then documentation PRs will be gladly accepted.

If you wish to discuss this further please take it to the mailing list as requested in both the README and the issue template you neglected to fill out.
