### ISSUE TITLE
Setting input type file with jQuery file upload is not working after update from 3.0.0.rc2 to 3.0.0

### ISSUE THREAD

**Issue by nagyt234** [teamcapybara/capybara#2089]
## Meta
Capybara Version: 3.0.0 - 3.6.0 (3.0.0.rc2 works as expected)
Driver Information (and browser if relevant): selenium-webdriver 3.14.0 with Firefox 61.0.1

## Expected Behavior
I'm using jquery-fileupload. The HTML code around the file input:
```
<!-- The fileinput-button span is used to style the file input field as button -->
<span class="btn btn-sm btn-success fileinput-button">
  <i class="icon-plus icon-white"></i>
  <span>Select and Upload File(s)</span>
  <input multiple="multiple" type="file" name="upload[upload][]" id="upload_upload" />
</span>
```
 The following test code should start the file upload.
`page.find("#upload_upload", visible:false).set(path1)`

## Actual Behavior
Instead of setting the path in the input the text in the button disappears and it raises the following error:
```
  1) FileAsset Pages New-Create (unattached file) Without Authorizations create with all required fields filled redirects back to the file assets list
     Failure/Error: page.find("#upload_upload", visible:false).set(path1)
     
     Selenium::WebDriver::Error::ElementNotInteractableError:
       Element <input id="upload_upload" name="upload[upload]" type="file"> could not be scrolled into view
     # WebDriverError@chrome://marionette/content/error.js:178:5
     # ElementNotInteractableError@chrome://marionette/content/error.js:286:5
     # interaction.clearElement@chrome://marionette/content/interaction.js:327:11
     # clearElement@chrome://marionette/content/listener.js:1329:3
     # dispatch/</req<@chrome://marionette/content/listener.js:491:14
     # dispatch/<@chrome://marionette/content/listener.js:484:15
     # ./spec/features/file_asset_pages_js_spec.rb:525:in `block (4 levels) in <top (required)>'
```
Note I tried a lot of variants, the result was the same:
attach_file('upload_upload', path1, make_visible: true)

attach_file('upload_upload', path1, visible: false)

script = "$('#upload_upload').css({opacity: 100, display: 'block'})\;"
page.driver.browser.execute_script(script)
attach_file('upload_upload', path1, visible: false)

## Steps to reproduce
Create the HTML above with jQuery file upload. And try to set the input.

**Comment by nagyt234** [comment]
The error is always the same.

The relevant CSS:

input[type="file"] {
    display: block;
}
.fileinput-button input { /* jquery-fileupload-ui.css */
￼    position: absolute;
￼    top: 0;
￼    right: 0;
￼    margin: 0;
￼    border: solid transparent;
￼    border-width: 0 0 100px 200px;
￼    opacity: 0;
    filter: alpha(opacity=0);
    -moz-transform: translate(-300px, 0) scale(4);
￼    direction: ltr;
￼    cursor: pointer;
}

**Comment by twalpole** [comment]
There is no change between 3.0.0.rc2 and 3.0.0 that would affect this at all, which means you probably also updated Firefox/geckodriver and or jquery-fileupload (which changed the CSS used) at the same time.  The issue is a change in behavior of FF/geckodriver where it appears to need to scroll the middle of an element into view rather than just any part of the element being visible. The CSS Capybara is using when the `make_visible` option is specified isn't enough to do that in this case.  That is also why the `make_visible` option can be set to a hash of CSS properties rather than just `true` and then the provided CSS properties will override the normal ones used.  The key is to specify properties that will get the file input visible and small enough to be fully visible inside the wrapping span.  In your case that might be something like

    attach_file('upload_upload', path, make_visible: { left: 0, opacity: 1, "border-width" => "0", transform: "none", "font-size" => "1px"})

although without an example to try it against I can't really confirm the exact CSS that will work for you.

**Comment by twalpole** [comment]
Note, there is an issue in Capybara where the styles applied by `make_visible` won't override any existing style that is specified as !important -- That will be fixed in the master branch shortly and be in release 3.7.0

**Comment by nagyt234** [comment]
Although the only change is definitely the capybara version between the working and non-working tests, your suggestion with the CSS hash is working correctly with Capybara 3.6.0. So I closed the issue.
Thanks for your help.
