### ISSUE TITLE
fill_in change event triggering discrepancy

### ISSUE THREAD

**Issue by benmmurphy** [teamcapybara/capybara#2105]
## Meta
Capybara Version:
3.8.2
Driver Information:
selenium-webdriver: 3.14.0
poltergeist: 1.18.1
chrome:  69.0.3497.100
chrome-driver: 2.42.591059

## Expected Behavior

When doing fill_in <field>, <value> all the drivers would either trigger the change event or none of the drivers would trigger the change event.

## Actual Behavior

Poltergeist: triggers the change event
Safari: does not trigger the change event
Firefox: does not trigger the change event
Chrome: does not trigger the change event

## Steps to reproduce

```
<script type='text/javascript'>
  document.addEventListener("DOMContentLoaded", function() {
    document.getElementById("foo").addEventListener("change", function() {
      document.getElementById("output").innerText = ("O" + "UTPUT");
    });
  });
</script>
<input type="text" name="foo" id="foo"/>

<div id="output"></div>
```

```class RootsTest < ApplicationSystemTestCase
   test "visiting the index" do
     visit root_index_path
     fill_in "foo", with: "hello world"
     assert_text "OUTPUT"
   end
```

**Comment by twalpole** [comment]
This is behaving as expected - All the modern browsers are behaving the same, and poltergeist/phantomjs (which is basically equivalent to a 7 year old version of Safari). Over the years when the change event has been fired has been different, but most modern browsers now implement that it doesn't fire for input type="text" elements until the element loses focus.  If you want to ensure the change event has fired after calling `fill_in` that means you will need to ensure the input loses focus by doing something like clicking on a different element.  If you think Poltergeist is doing something wrong here, then you should report it to the Poltergeist project, although since PhantomJS has been abandoned the Poltergeist project really isn't getting updated much anymore.
