### ISSUE TITLE
Chromedriver 73 fails on Docker

### ISSUE THREAD

**Issue by toupeira** [teamcapybara/capybara#2164]
## Meta
Capybara Version:
3.14.0
Driver Information (and browser if relevant):
selenium-webdriver 3.141.0 with Google Chrome 73.0.3683.75-1 and chromedriver 73.0.3683.68

## Expected Behavior

Chromedriver should work normally on Docker (running in GitLab CI).

## Actual Behavior

Chromedriver fails with the following exception:

```
Selenium::WebDriver::Error::UnknownError:
  unknown error: Chrome failed to start: exited abnormally
    (unknown error: DevToolsActivePort file doesn't exist)
    (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
    (Driver info: chromedriver=73.0.3683.68 (47787ec04b6e38e22703e856e101e840b65afe72),platform=Linux 4.14.65+ x86_64)
```

## Workaround

I found https://bugs.chromium.org/p/chromedriver/issues/detail?id=2473, adding `--no-sandbox` makes it work again. The other suggested option `--disable-dev-shm-usage` wasn't necessary for me.

Probably `--no-sandbox` can be added to the `:selenium_chrome_headless` driver definition in the Capybara gem?

**Comment by twalpole** [comment]
@toupeira We can't configure the pre-registered drivers to be compatible with all platforms. Because  including `--no-sandbox` is a potential security issue on systems that don't absolutely require it, and the fact that using `--no-sandbox` it is generally a hack around other system configuration/permissions issues, we won't be updating the default driver registrations.  If your use case needs `--no-sandbox` you'll need to register your own driver configuration.

**Comment by toupeira** [comment]
@twalpole fair enough! :+1:

**Comment by fabn** [comment]
Useful report, thanks.

An alternative could be to provide a capybara options, something like 

```
Capybara.use_no_sanbox = true
```

To allow tweak of this behavior without redefining `headless_chrome` for every project. I think nowadays is pretty common to run specs in docker environments so this could be useful.

Just my two cents.
