### ISSUE TITLE
Feature Request: Add config to enable remote debugger when using headless browsers

### ISSUE THREAD

**Issue by ThisIsMissEm** [teamcapybara/capybara#2174]
Hi! I recently came across an interesting bug in our tests, and the only way that I was able to work out what was going on was by enabling chrome's remote debugger and inspect elements/checking things.

In order to do this, I had to create a custom Capybara driver, with the following:

```ruby
Capybara.register_driver :selenium_chrome_headless_debug do |app|
  Capybara::Selenium::Driver.load_selenium
  browser_options = ::Selenium::WebDriver::Chrome::Options.new.tap do |opts|
    opts.args << '--headless'
    opts.args << '--disable-gpu' if Gem.win_platform?
    # Workaround https://bugs.chromium.org/p/chromedriver/issues/detail?id=2650&q=load&sort=-id&colspec=ID%20Status%20Pri%20Owner%20Summary
    opts.args << '--disable-site-isolation-trials'
    opts.args << '--remote-debugging-port=9222'
  end
  Capybara::Selenium::Driver.new(app, browser: :chrome, options: browser_options)
end
```

It'd be amazing to have Capybara add an option to add the argument: `    opts.args << '--remote-debugging-port=9222'` if the option is set to true; that way a standard browser feature would be able to be enabled without completely custom Driver setup.

I've seen previous feature requests denied for compatibility issues, so I've checked, and both Firefox and Chrome support some form of remote debugging:
- https://developers.google.com/web/updates/2017/04/headless-chrome#frontend
- https://developer.mozilla.org/en-US/docs/Tools/Remote_Debugging/Debugging_Firefox_Desktop#Firefox_37_onwards

## Meta
Capybara Version: 3.10.1
Driver Information (and browser if relevant): selenium_chrome_headless, using webdrivers and selenium-webdriver

## Addendum:

Turns out my issue I was having was because seemingly by default `selenium_chrome_headless` runs in a window size that triggers responsive css rules, which meant that yes, the button I was trying to target was indeed hidden, despite the fact that I could see it in a screenshot — that was actually a different button with the same text and styling. 🤦‍♀️ 

I've since added this to my configuration to avoid this issue:

```ruby
RSpec.configure do |config|
  config.before(:each, js: true) do
    Capybara.page.driver.browser.manage.window.maximize
    Capybara.page.driver.browser.manage.window.resize_to(1440, 900)
  end
end
```

**Comment by ThisIsMissEm** [comment]
I'm thinking something like the following would work:

```ruby
Capybara.configure do |config|
  config.enable_remote_debugging = true
end
```

or:

```ruby
Capybara.configure do |config|
  config.remote_debugging_port = 9222
end
```

**Comment by twalpole** [comment]
Unfortunately we can't register drivers for every combination of options people may need, which is exactly why we allow people to register their own driver configs.  If you could come up with a backwards compatible way to make the pre-registered drivers derivable/configurable I would consider that  Additionally configuration of Selenium drivers will be changing when selenium-webdriver v4 is released so we will probably need to take another look when that change happens, and may reconsider then (although I really want to reduce the number of Capybaras configurable options rather than increase them if possible).  I would accept a PR for the README that shows remote debugging configuration in the drivers examples though.
