### ISSUE TITLE
Can't set screen_size on drivers provided by Capybara

### ISSUE THREAD

**Issue by aried3r** [teamcapybara/capybara#2219]
I'm not sure if this is a usage question or a bug, but if it's not a bug, I'll be glad to ask on the mailing list.

## Meta
Capybara Version:
3.23.0
Driver Information (and browser if relevant):
selenium-webdriver with Chrome 75.0.3770.80 via `webdrivers` gem

## Description

This should set the screen size for `:selenium_chrome_headless`, but doesn't.

```Ruby
RSpec.configure do |config|
  config.before(:each, type: :system) do
    driven_by :selenium_chrome_headless, screen_size: [1400, 1400]
  end
end
```

Neither does

```Ruby
driven_by :selenium, using: :selenium_chrome_headless, screen_size: [1400, 1400]

# ArgumentError:
#              unknown driver: :selenium_chrome_headless
```

The following works, but doesn't actually use the driver defined by capybara, which I'd like to use. I know I could `.tap` into the configuration etc, but I'd love to go with the public API provided.

```
RSpec.configure do |config|
  config.before(:each, type: :system) do
    driven_by :selenium, using: :headless_chrome, screen_size: [1400, 1400]
  end
end
```

**Comment by twalpole** [comment]
This is functionality provided by Rails, and as such they only provide it for drivers they register - https://github.com/rails/rails/blob/master/actionpack/lib/action_dispatch/system_testing/driver.rb#L45. - and for some reason they don't even use the Capybara public API for setting the size.  I'm not really sure what you would expect Capybara to do around this?

**Comment by aried3r** [comment]
> This is functionality provided by Rails

Ah, I didn't know it came from Rails itself. I guess this should have been posted to the Google group after all, I'm sorry.

Instead of moving the discussion there, I'd like to resolve this here if that's ok with you.

> I'm not really sure what you would expect Capybara to do around this?

I think what I'm most interested in would be an official guide added to the README on how capybara suggests adding, modifying etc driver settings, especially screen size. 
People on StackOverflow suggest either [registering a new driver](https://stackoverflow.com/questions/47182364/how-to-set-screen-size-for-chrome-headless-system-test-in-rails-5-1/47290251) or `.tap`ing into existing ones (much like [capybara does](https://github.com/teamcapybara/capybara/blob/c7c22789b7aaf6c1515bf6e68f00bfe074cf8fc1/lib/capybara/registrations/drivers.rb#L29), but I feel that might be a bit brittle, since I do enjoy Capybara and Rails providing and maintaining their own [set of rules](https://github.com/teamcapybara/capybara/blob/c7c22789b7aaf6c1515bf6e68f00bfe074cf8fc1/lib/capybara/registrations/drivers.rb#L32-L33) with workarounds if necessary.

> for some reason they don't even use the Capybara public API for setting the size

Adding to what I've written above, what is the preferred way and is there something we could do to better things on the Rails side of things as well? :)

PS: I was wondering if capybara should maybe use the provided Selenium APIs to add and modify arguments instead of `.tap`ing into them, given that the result is the same. I think it's more a question of code style and I don't have strong opinions on it either way. Since you also work on Selenium I guess you are aware of the [little helpers](https://github.com/SeleniumHQ/selenium/blob/3d119e1550dee6a1aa8e30c533d7f71e2cf099c6/rb/lib/selenium/webdriver/chrome/options.rb#L138-L140) it provides.

**Comment by twalpole** [comment]
The official guide is the README where it talks about registering your own driver - https://github.com/teamcapybara/capybara#configuring-and-adding-drivers .  Other than that, if using Rails with system tests and `driven_by` you need to see their docs for what to do and how that works (would actually clear up some confusion for Rails users if `driven_by` issued a warning when passed options that weren't actually being applied due to specifying non Rails registered drivers).

You mention registering a new driver or tapping into existing drivers as if they're different things - they're not. `tap` is just used to allow to return the original object while performing some actions on it.  It's used purely as a way to wrap the configuration of the object in a block to make the code clearer.
It could just as easily have been written

    browser_options = ::Selenium::WebDriver::Chrome::Options.new     
    browser_options.args << '--headless'
    browser_options.args << '--disable-gpu' if Gem.win_platform?
    browser_options.args << '--disable-site-isolation-trials'

As far as Capybara is concerned if you need driver settings other than the ones provided by Capybara then you should register your own driver.  If using Rails and `driven_by` they have provided extra syntactic sugar on top where you can pass in different options and it will register a new driver for you (and keep re-registering it over and over for some reason I believe). You'd need to check the Rails docs for the exact syntax of that and whether or not you wish to use that functionality is purely up to you (I don't use that functionality in my projects using Rails).  

As for your last comment about the public Selenium APIs - Capybara is using the public APIs to configure Selenium (`Options#args` is public API). The reason the `headless!` helper isn't used in the 
publicly registered drivers is because it wasn't added to Selenium until 3.10 and Capybara technically supports versions less than that.  The helper, however, is used in the drivers registered in Capybaras tests - https://github.com/teamcapybara/capybara/blob/master/spec/selenium_spec_chrome.rb#L14 - where we know the version of Selenium being used

**Comment by aried3r** [comment]
Thanks for the extensive answer, I have a better understanding now of how things work!

> I don't use that functionality in my projects using Rails

Would you mind showing me how you use it? I think a complete example in the README would maybe help other people as well.

I think I didn't do the best job of explaining what I was actually after. I've seen the capybara registered drivers and all the options they provide, I'd love to use them, because they are maintained within capybara itself (workaround arguments like I mentioned or optional ones depending on the platform) and just adjust the screen/window size instead of having to register my own driver and having to maintain all that myself.

I guess what I'm asking is, if I can't use the capybara drivers directly using the Rails API, is there a way to `.tap` into the capybara drivers like capybara does with the Selenium ones (`::Selenium::WebDriver::Chrome::Options.new.tap
`)? I only know the symbol to use (e.g. `:selenium_chrome_headless`), but not how to change or add arguments.

**Comment by twalpole** [comment]
You can use the capybara drivers directly with the `:using` parameter of `driven_by` - but you can't specify options with it.  I think your issue here is with the Rails documentation around `driven_by`.  

No you can't `tap` into the capybara drivers, you need to register your own driver if you want other options.  As for changing options/arguments that's Selenium specific (notice the namespace of the Options object)
