### ISSUE TITLE
Print Dialog does not close in Firefox Selenium Driver

### ISSUE THREAD

**Issue by JohnMerlino2** [teamcapybara/capybara#2243]
I am using Capybara with the Firefox Selenium Driver. In my feature test, I test that the print page has a certain number of rows in a table. Everything runs and test passes. Unfortunately, this print dialog box remains open for the other tests that run:

![print-dialog](https://user-images.githubusercontent.com/22782195/64463163-01e46b80-d0d1-11e9-97cc-e2f1c4f568e6.png)

Now in the open browser, I can press the escape key to make the dialog go away. But when I try to do it with Capybara, it does not go away:

`page.driver.browser.action.send_keys(:escape).perform
`

Why does the above code not work, even though when I press escape key on keyboard manually it does work?

**Comment by twalpole** [comment]
The only "system" dialogs the webdriver spec allows to interact with are the 'alert', 'confirm', and 'prompt' boxes.  The 'print' dialog isn't one of those and the 'esc' key needs to be sent to it for it to close, whereas send_keys will send to the active element in the page since it knows nothing about the print dialog.  If you need to test pages that open the print dialog you probably want to be doing that in a second tab which you can then close, or a second session (browser instance).
