### ISSUE TITLE
Attempting to find the label for an element fails when that element does not have an id attribute

### ISSUE THREAD

**Issue by Fitzsimmons** [teamcapybara/capybara#2260]
## Meta
Capybara Version:
`3.29.0`

Driver Information (and browser if relevant):
`ChromeDriver 76.0.3809.68 (420c9498db8ce8fcd190a954d51297672c1515d5-refs/branch-heads/3809@{#864})`

## Expected Behavior

Given the example html:

```html
<label>Hello
  <input type="checkbox" />
</label>
```

and the following code:

```ruby
el = find("input")
label = el.session.find(:label, for: el)

label.click
```

It should find the label and click it.

## Actual Behavior

The label is not found, with the following error:

> Capybara::ElementNotFound: Unable to find label nil

We can work around the error by adding an id to the input.

```html
<label>Hello
  <input type="checkbox" id="fjewio" />
</label>
```

## Conclusion

The defect appears to be on [line 13 of label.rb](https://github.com/teamcapybara/capybara/blob/120714984f31d896ec35ff1c99606902734f7b79/lib/capybara/selector/definition/label.rb#L13), where it attempts to read the id attribute of an element that does not have an id.

We found this because it's on the critical path for the `allow_label_click` option, causing Capybara to not be able to find the label unless the invisible element has an id.

I don't feel confident enough with Capybara's internals to propose a patch for this, unfortunately.

**Comment by twalpole** [comment]
Actually when the element doesn't have an id it should be handled in https://github.com/teamcapybara/capybara/blob/120714984f31d896ec35ff1c99606902734f7b79/lib/capybara/selector/definition/label.rb#L29 since in line 13 `for_option` should be nil and therefore not apply that part of the XPath.  I'll try and take a look later today, but I'm pretty sure there are tests for this behavior - https://github.com/teamcapybara/capybara/blob/29e86bd9fc4bb76acc591cba12ee6c373176eef6/lib/capybara/spec/session/selectors_spec.rb#L29

**Comment by twalpole** [comment]
Please try the master branch - should be fixed.
