### ISSUE TITLE
Capybara should ignore text that's hidden via `clip` property

### ISSUE THREAD

**Issue by sharmarahul** [teamcapybara/capybara#2272]
Capybara Version:
3.29.0

Driver Information (and browser if relevant):
Selenium-Webdriver - Chromedriver

When retrieving a node's text, elements that are hidden by setting `clip` property are returned by Capybara. This text is hidden in this way so that screen readers can read it. 

Such text should not be returned?

## Actual Behavior
Text that is not set as `display:none` but is hidden as `clip: rect(0 0 0 0)!important;` is treated as visible text despite being not visible.

**Comment by twalpole** [comment]
This is a serious edge case - but could be fixed in the JS used to identify whether elements are visible or not - for capybara optimizations that would be https://github.com/teamcapybara/capybara/blob/master/lib/capybara/selenium/atoms/src/isDisplayed.js - although selenium-webdriver has its own version too.  If it's important to you PRs are welcome, I currently don't know how `clip` interacts with other CSS so I don't know what the edge cases around the edge case would be.

**Comment by twalpole** [comment]
Also note - if handling this, you'd probably also want to handle `clipPath` - and you'd have to ensure the element was fixed or absolute positioned, etc -- it gets complicated to do correctly very quickly.

**Comment by twalpole** [comment]
Closing this because I consider it a rare edge case.  If someone wants to implement it and consider all the cases around clipping PRs will be considered.
