### ISSUE TITLE
`expect(page).to match(/foobarbaz/)` passes

### ISSUE THREAD

**Issue by boris-petrov** [teamcapybara/capybara#2281]
Capybara version 3.29.0. Having this code:

```ruby
expect(page).to match(/foobarbaz/)
```

For any regex, does nothing. It just passes through and continues on. I understand that the code is wrong and should be `page.text`, but it would be nice for that to fail so people don't write stuff that they expect checks something but it actually just silently does nothing.

**Comment by twalpole** [comment]
That should NoT be written as `page.text` it should be written as `expect(page).to have_text(/foobarbaz/)` . As for this issue, I don’t think there’s anything Capybara can do around this because `match` isn’t a Capybara provided matcher.

**Comment by boris-petrov** [comment]
Ah, I see. That's a pity because it really might bite someone... as it did me. But OK, in that case, I'll leave you to close the issue if you think there is nothing to be done. Thanks!

**Comment by twalpole** [comment]
Looking at this closer, even though Capybara doesn't provide the `match` matcher - unless you're doing something very strange with `page` or RSpecs matchers - there's no way your expectation should ever pass since `page` would convert to `#<Capybara::Session>` as a string.  So without an example showing this issue I have no clue how you're getting that to pass.
