### ISSUE TITLE
have_content matcher around 6 times slower on `page` than on `page.body`

### ISSUE THREAD

**Issue by manueljacob** [teamcapybara/capybara#2296]
Capybara Version: 3.30.0

```
require 'rails_helper'

RSpec.describe 'foo', type: :feature do
	[:rack_test, :selenium_chrome_headless].each do |driver|
		context "with driver #{driver}", driver: driver do
			it "contains 'foo'" do
				visit '/foo'
				n = 1000
				Benchmark.bm do |x|
					x.report { n.times { expect(page     ).to have_content('foo') } }
					x.report { n.times { expect(page.body).to have_content('foo') } }
				end
			end
		end
	end
end
```

The route `/foo` returns just "foo".

Although the two expectations seem to be equivalent sementically, using `page` is around 6 times slower than using `page.body`.

With driver `:rack_test`:

```
       user     system      total        real
   0.657643   0.077398   0.735041 (  0.751118)
   0.104262   0.009484   0.113746 (  0.115250)
```

With driver `:selenium_chrome_headless`:

```
       user     system      total        real
   4.820990   0.499450   5.320440 ( 26.274950)
   1.496166   0.170787   1.666953 (  4.368785)
```

I was going to recommend using `page` over `page.body` in our style guide because it seems more idiomatic, but given the performance impact I should consider doing it the other way around.

Is there a way to make using `page` as fast as using `page.body`?

**Comment by twalpole** [comment]
This is expected because running an assertion on `page` is not the same as running it on `page.body`. `body`, `html`, and `source` are all aliases of each other and return the HTML source of the page as a string. Using `page.body` would therefore cause the assertion to run against the string rather than the dynamic page, and all retries of the assertion would be run against the same string meaning it would be useless on dynamic pages.  You should definitely not be recommending asserting on `page.body` rather than `page` unless you want to start dealing with all sorts of flaky issues.

**Comment by manueljacob** [comment]
@twalpole https://rubydoc.info/github/jnicklas/capybara/master/Capybara%2FSession:html sounds like it works against the dynamic page.

Still, it seems to be better to use `page` than `page.body` because of #792.

**Comment by twalpole** [comment]
@manueljacob youre not understanding Capybaras built-in retry behavior - `page.body` will get a snapshot of the page (yes of the dynamic page but the snapshot will be static).  That means any call to a Capybara provided assertion/matches would not be retrying against the dynamic page. When you use just `page` the assertions/marchers would. Internally retry against the dynamic page (not a static snapshot). As I said you should definitely not be recommending ‘page.body’ over ‘page’
