### ISSUE TITLE
Newline character becomes \r\n

### ISSUE THREAD

**Issue by willawill** [teamcapybara/capybara#2313]
Capybara Version: 3.13

I was in the middle of upgrading capybara for our codebase from 3.12.0 to the latest. I noticed all the tests are failing due to the extra newline character `\r\n` from `\n`. Is this on purpose? 

If so, what's the best way to go about it? I'd like to avoid this kind of global replacement if its possible. Also Would there be more updates on `Node#text` handling whitespaces in the future? 

Thanks!

**Comment by twalpole** [comment]
The Changes from 3.12 -> 3.13 are listed at https://github.com/teamcapybara/capybara/blob/master/History.md#version-3130 and there doesn't appear to be anything around getting of text, etc.  So without details about what driver you're using, and what exactly you're testing it's impossible to say what you're seeing.

**Comment by willawill** [comment]
My apologies for lacking of context.

Driver: geckodriver 0.26.0
browser: firefox 72.0.2

Among many failures, one test we have is a mailer_spec.rb with rspec.

```
    it 'sends the correct email' do
      expect(mail).to deliver_from(default_from)
      expect(mail).to deliver_to 'Jon Snow <jon@thewall.com>'
      expect(mail).to have_subject 'Your application to QA Intern'

      mail_body = <<~TEXT
        Hi Jon,

        Your application to Organization for Chef failed
        to process completely. Please revisit their careers page to resubmit your application.
      TEXT

      expect(mail).to have_content mail_body
    end
```

The failure I am seeing is 
```
expected to find text "Hi Jon,\n\nYour application to...
...
in
"Hi Jon,\r\n\r\nYour application to"
```
We have capybara.match to set to `:smart` we don't have `default_normalize_whitespace` option on.

I've upgraded all the dependencies (nokogiri, regexp_parser, rack, public_suffix) one by one and they didn't seem to cause the failure. Any help would be appreciated!

**Comment by twalpole** [comment]
The code changes from 3.12.0 to 3.13.0 (is there a reason you're going to 3.13.0 and not 3.31.0?) can be seen at https://github.com/teamcapybara/capybara/compare/3.12.0...3.13.0 . I don't see anything in there that would affect Capybaras parsing of text, unless you have nokogumbo installed and set Capybara.allow_gumbo to true. 

Are you using a gem to handle email testing?  because generally Capybara can't be used with just a random string (it needs to be HTML for it to parse it correctly) so it may be these tests aren't even using Capybara, and instead are just using the RSpec `have_xxxx` matcher in this case which would call `has_content?` on whatever `mail` is.

**Comment by twalpole** [comment]
Another thing to check is if you've been editing your tests in OSX when they were first written in Windows or vice versa, that your editor settings are set to save the files in the original format \n vs \r\n

**Comment by twalpole** [comment]
Closing this because I can't replicate it, and I think it's probably not actually Capybara being used in the example shown.  If you can provide a self contained example (http://sscce.org/) that illustrates the issue when run on 3.12 vs 3.13 I will reopen this and either fix or explain what's going on
