### ISSUE TITLE
has_description? matcher

### ISSUE THREAD

**Issue by dkniffin** [teamcapybara/capybara#2330]
There is already a `has_title?` method/matcher that checks the page's title metatag. I would like for there to be a `has_description?` matcher that does the same thing for description meta_tag

Example usage:
```rb
expect(page).to have_description("A super awesome page about whatever")
```

**Comment by twalpole** [comment]
There is a `has_title`  matcher because it's actually shown to the end user, and there is a \<title> element  whereas `description` really isn't shown to the user and there is no such thing as a \<description> element. There could be an argument for a have_meta type matcher, but I think `have_description` really doesn't justify expanding the api.  If you really need this, you can implement your own in a helper method like

    def have_description(desc)
      have_xpath(XPath.anywhere(:meta)[XPath.attr(:name) == 'description'][XPath.attr(:content) == desc], visible: false)
    end

**Comment by dkniffin** [comment]
@twalpole I understand. That makes sense. I would like the `have_meta` matcher though. Should I make a new issue for that?

**Comment by twalpole** [comment]
A PR would be better :)

-- Thomas

**Comment by twalpole** [comment]
Also, I'm not fully convinced of the need for `have_meta` since it's so simple to implement yourself if you need it

    def have_meta(name, content)
      have_xpath(XPath.anywhere(:meta)[XPath.attr(name.to_sym) == 'description'][XPath.attr(:content) == content], visible: false)
    end
