### ISSUE TITLE
New rapid `.set()` fails to trigger onChange (?)

### ISSUE THREAD

**Issue by bwreid** [teamcapybara/capybara#2331]
## Meta

Capybara Version: **3.32.0**
Driver Information (and browser if relevant): **selenium-webdriver 3.142.7 with Chrome 80.0.3987.149**

## Expected Behavior

We are trying to update to Capybara's latest version and had a test that was succeeding fail in this newest version. In our test, we take an encoded URL from Wikipedia and "set" it into an input field. Our project is open source, so you can see the exact test at [this link.](https://github.com/WikiEducationFoundation/WikiEduDashboard/blob/master/spec/features/multiwiki_assignment_spec.rb#L20-L42). We then have a function that decodes the long URL and displays it to the user. Part of the decoded URL should show up on the page so that the test passes.

## Actual Behavior

With the new change, this test is now failing with the error: "Uncaught URIError: URI malformed". We've added `rapid: false` to disable this feature, but I believe it is unintended.

## Steps to reproduce

See code above. I believe you can reproduce this error by attempting to provide any kind of `onChange` event. In this case, the value of the input field is as follows:

```
https://ta.wiktionary.org/wiki/%E0%AE%86%E0%AE%99%E0%AF%8D%E0%AE%95%E0%AE%BF%E0%AE%B2%E0%AE%AE%E0%AF%8D
```

The changes that this URL is processed through can be found in [this function.](https://github.com/WikiEducationFoundation/WikiEduDashboard/blob/master/app/assets/javascripts/utils/course_utils.js#L56-L100)

**Comment by twalpole** [comment]
So you're attempting to set the value to `https://ta.wiktionary.org/wiki/%E0%AE%86%E0%AE%99%E0%AF%8D%E0%AE%95%E0%AE%BF%E0%AE%B2%E0%AE%AE%E0%AF%8D` but what does the value actually get set to that generates the URI Error ?

**Comment by twalpole** [comment]
Also, if you could make a self contained example that demonstrates the issue it would help a lot - the requirements for installing the project the test is from really aren't reasonable for trying to diagnose this issue

**Comment by twalpole** [comment]
I can't replicate this issue with the information provided - I've added a test to the Capybara test suite which fills in a react field that has an onchange handler, and it works fine.  I really need a self contained example to be able to diagnose this.

**Comment by ragesoss** [comment]
Thanks @twalpole! I started digging to figure out what was going wrong, and it's definitely a peculiarity of our app rather than a bug in Capybara.

Here's the explanation: we have an input field that handles Wikipedia (and other Wikimedia project) articles; this can take the form of either just a title (with the specific language assumed) or an entire URL for an article. If you put in a URL, there's a function that extracts the beginning of it, eg, `https://ta.wiktionary.org/wiki/` to identify the specific wiki the article is from, and then sets the remainder of the input as the article title. If the input doesn't start with `http` then it just treats it like a plain title rather than a URL.

The resulting behavior is that, if you start typing in a URL like the example above, one character at a time, then once you reach "https://ta.wiktionary.org/wiki/" as the input, the input value gets set to an empty string, the wiki gets updated to `ta.wiktionary.org`, and then as typing continues, it gets treated as just an article title, not a URL.

With fast input, it jumps straight from "http" to almost (but not quite) the full URL: "https://ta.wiktionary.org/wiki/%E0%AE%86%E0%AE%99%E0%AF%8D%E0%AE%95%E0%AE%BF%E0%AE%B2%E0%AE%AE%E0%AF%".

That's an invalid URI (missing the last two characters of the intended input), and because there wasn't already valid URI that caused our code to extract and remove the "https://ta.wiktionary.org/wiki/" part, it breaks our code.

**Comment by bwreid** [comment]
Closing issue thanks to @ragesoss. Thanks for taking a look.
