### ISSUE TITLE
can we add a way to ignore obscured elements by default?

### ISSUE THREAD

**Issue by dreyks** [teamcapybara/capybara#2336]
Not a bug but a suggestion: do you think it would be beneficial to have a global session setting to control the default obscured option in `matches_visibility_filters?`?
Similar to how `Capybara.ignore_hidden_elements` controls the default visibility part

**Comment by twalpole** [comment]
The issue with `obscured` is that its performance hit is pretty large, for no real gain in a general use case.  I'd actually prefer to remove the `ignore_hidden_elements` setting since too many people shoot themselves in the foot with it, but legacy...  

`obscured` generally makes more sense in an expectation/assertion setting rather than a finding setting (since found obscured elements can generally be scrolled into view when being interacted with), what is your use case where you would actually want obscured to default to being used?

**Comment by dreyks** [comment]
i'm currently working with modals and want to assert that a certain button is present on a modal and not under it (which can also happen). So my intention is that as a user if i can't click the element because it's covered by an overlay - then i don't "see" it

**Comment by dreyks** [comment]
maybe we could have a way of at least scope this check? something like 
```rb
with_non_obscured_only do
  # expectations
end
```

**Comment by twalpole** [comment]
Whats the use case?

**Comment by twalpole** [comment]
Why wouldn't you just assert that it's inside the modal?

    within '#modal' do
      # expectations
    end

There's no way for elements in the modal to be under it

**Comment by dreyks** [comment]
i’m trying to test based on what a user can see, so that the tests resemble real usage: text, titles instead of classnames and ids

**Comment by twalpole** [comment]
Ok - you could create a custom selector for your modals and then do something like

    within :modal, 'my modal title' do
      # expectations
    end

Anyway, I'm not sure providing people a way to use `obscured` everywhere is encouraging great practices.  If you feel you must have it for your own project, I'd recommend prepending a module on Capybara::Quereies::SelectorQuery which provides `matches_filters?` and boils down to something along the lines of 

    def matches_filters?...)
      super && !node.obscured?
    end

when you want obscured checked for all elements.

**Comment by dreyks** [comment]
thx! will investigate
