### ISSUE TITLE
save_and_open_screenshot broken

### ISSUE THREAD

**Issue by jtmkrueger** [teamcapybara/capybara#2337]
**Note:** This is for issues with Capybara.  If you have a howto type question, please ask on the mailing list as requested in the README: http://groups.google.com/group/ruby-capybara

## Meta
Capybara Version: 3.32.0

## Expected Behavior
`save_and_open_screenshot` to open a screenshot

## Actual Behavior
```
Failure/Error: save_and_open_screenshot

Capybara::NotSupportedByDriverError:
  Capybara::Driver::Base#save_screenshot
```

## Steps to reproduce
Put `save_and_open_screenshot` in a test.

_EDIT: updated version I'm using_

**Comment by twalpole** [comment]
The error fully explains what the issue is - The driver you're using doesn't support screenshots - What driver are you using?  If I had to guess probably the rack-test driver, which doesn't actually render the page so can't generate screenshots - See https://github.com/teamcapybara/capybara#drivers

**Comment by jtmkrueger** [comment]
`gem "selenium-webdriver"`

**Comment by jtmkrueger** [comment]
so @twalpole you think the problem is probably there?

**Comment by jtmkrueger** [comment]
I also have blocks set up to register these drivers.

**Comment by jtmkrueger** [comment]
```
╰─ gem list | grep selenium
selenium-webdriver (3.142.7)
```
For reference.

**Comment by twalpole** [comment]
@jtmkrueger but are you actually using selenium for your tests? Selenium definitely supports screenshots and is part of Capybaras test suite so it definitely works.  Please look at the section I linked to on drivers and how to select the one you're using for your tests

**Comment by jtmkrueger** [comment]
> I also have blocks set up to register these drivers.

Yes, that's what I meant with this. This has been working for years up to now, so this is a new issue.

**Comment by twalpole** [comment]
@jtmkrueger The only way the error you show happens is if a call to a method ends up in the base driver class - https://github.com/teamcapybara/capybara/blob/master/lib/capybara/driver/base.rb#L50 - since the selenium driver has a `save_screenshot` method - https://github.com/teamcapybara/capybara/blob/master/lib/capybara/selenium/driver.rb#L116 - it wouldn't ever raise that error - which means you're not using the selenium driver in your test.  If it was previously working it means you've changed something in a way that it's no longer using the selenium driver for the test you're seeing the error from.  Look at the stacktrace for the error and I'll pretty much guarantee you'll see that you're using the `rack_test` driver for the test.

**Comment by jtmkrueger** [comment]
I figured out what was wrong, and it was completely user error. You're right I was using `rack_test` and that's what broke it. Sorry for the noise.
