### ISSUE TITLE
Xpath searching is broken

### ISSUE THREAD

**Issue by adisciple50** [teamcapybara/capybara#2338]
the xpath selector is broken.

 Failure/Error: expect(page).to have_xpath('//textarea[@autocorrect="off"]')
       expected to find visible xpath "//textarea[@autocorrect=\\"off\\"]" but there were no matches. Also found "", which matched the selector but not all filters.

the above xpath was found in google chrome developer tools

**Comment by adisciple50** [comment]
i have escaped the \\ for the sake of markdown.

**Comment by twalpole** [comment]
Word of advice, before you state that a widely used (some might say core) feature of a widely used gem is broken you should take the time to consider that maybe it's your usage of it and read the error messages you're getting more closely.

Yes Chrome will find that element, because Chrome doesn't care whether the element is visible on the page or not however Capybara, as stated in the error message, defaults to finding only visible elements (`expected to find **visible** xpath ...`).

If you are doing an expectation for a non-visible element then you'd need to do `expect(page).to have_xpath('//textarea[@Autocorrect="off"]', visible: :hidden)`. That being said, you really shouldn't be expecting for a non-visible element because if a user can't see them, they can't interact with them, and therefore testing for them doesn't make much sense in feature/system specs where user behavior is what you should be testing.
