### ISSUE TITLE
Timing issue causes input fields to not be filled out

### ISSUE THREAD

**Issue by Antsiscool** [teamcapybara/capybara#2342]
## Meta
Capybara Version:
3.32.1
Driver Information (and browser if relevant):
selenium-webdriver 3.142.7 with Google Chrome 81.0.4044.129 on macOS Catalina 10.15.4

Old laptop running same software on Mojave (10.14.6)

## Expected Behavior
I have just been setting up a new development machine. After installing all required software I have been attempting to run some specs.

Specs that pass on the old mac (And on the CI servers) should continue to pass on the new mac.

## Actual Behavior
When running specs with headless Chrome it will load the page and follow any links. However with it comes to an input field to type into. e.g. username field on login page. It will not enter any text. The fill_in command doesn't fail and the expectation on the following lines to check that it navigated to the correct page fail.

Saving a screenshot shows it at the previous page with no text in the entered field, but with an error about the missing text.

Running tests with visible Chrome shows the same behaviour. If I manually type the text into the field that it has failed to type and submit the form the test continues on.

Putting a sleep for 1 second before entering the text consistently fixes the problem.

No exceptions are raised about been unable to find the field or about problems entering the text.

This happens in all the specs on this new machine, but does not occur on my old development machine.

The only different between the two laptops is that the old mac is still running Mojave (10.14.6)

Is anyone aware of any timing issues with Google Chrome that could cause this?
Opening the developer console in Chrome also slows it down enough that all the tests pass.

**Comment by twalpole** [comment]
Without an example that shows the issues it's pretty impossible to say for sure what's happening, however since a sleep before filling in the field fixes the issue it sounds like the new machine is faster and is attempting to fill in the field before the page is actually ready to be interacted with.  This can happen if your page is attaching JS behavior to inputs but leaving them visible on the page before that happens. Capybara has no way of knowing if/when your fields are "ready" to be filled in if they are available on the page.

**Comment by twalpole** [comment]
Closing since no way to replicate has been provided - if one is provided we can reopen.

**Comment by knkarthik** [comment]
@Antsiscool I've experienced the same behaviour sometimes. In my case clicking the input before filling it seems to work 🤷
