### ISSUE TITLE
find_link does not ignore hidden text

### ISSUE THREAD

**Issue by javierm** [teamcapybara/capybara#2347]
## Meta

Capybara Version: Latest master as of 2020-05-10. I've also tested it with Capybara 3.32.1, 3.29.0 and 2.17.0, getting the same result.
Fails with several drivers (all of them?), as shown on this [Travis build based on master with a test showing the failure](https://travis-ci.org/github/javierm/capybara/builds/685359275).

## Steps to reproduce

Add the following line to `capybara/lib/capybara/spec/views/with_html.erb`:

```html
  <a href="/">Some of this text is <em style="display:none">hidden!</em></a>
```

And then run the following tests:

```ruby
context 'hidden text in links' do
  it 'ignores hidden text finding CSS' do
    expect(@session.find(:css, 'a', text: 'Some of this text is').text).to eq('Some of this text is')
    expect { @session.find(:css, 'a', text: 'Some of this text is hidden') }.to raise_error(Capybara::ElementNotFound)
  end

  it 'ignores hidden text finding links' do
    expect(@session.find_link('Some of this text is').text).to eq('Some of this text is')
    expect(@session.find_link('Some of this text is', exact: true).text).to eq('Some of this text is')
    expect { @session.find_link('Some of this text is hidden') }.to raise_error(Capybara::ElementNotFound)
  end
end
```

## Expected Behavior

Both tests pass.

## Actual Behavior

Only the first test passes. In the second one, the first expectation passes, but the second one fails (and I think the third one fails too).

I'm afraid I haven't been able to find what's causing the issue, so I can't open a pull request fixing it. Sorry for that! :pray:

**Comment by twalpole** [comment]
This is by design.  Visibility of the locator passed to selectors is not considered, only the visibility of the element found by that locator matters.  In the case of the `link` selector the locator is compared against the id, title, text contents, alt attribute of a descendant img, aria-label (if enabled), and a test id (if enabled).  This is all done directly via an XPath expression, after which any matching elements are checked for visibility (in default configuration). If you want to use `find_link` to match against contained text with visibility taken into account you need to use the `:text` or `:exact_text` options.

    find_link(exact_text: 'Some of this text is')

Note: that is MUCH slower than `find_link('Some of this text is')` but if it's the behavior you want/need then you need to take the performance hit. You can minimize some of the performance hit by using a selector or other expression options that would narrow down the number of links that would need to be checked
 
    find_link('Some of this text is', exact_text: 'Some of this text is')
    find_link(href: '/', exact_text: 'Some of this text is')

**Comment by javierm** [comment]
:facepalm:. I'm very sorry to have opened an issue :pray:. Next time I'll use the mailing list even if I'm almost sure it's a bug!

Thank you so much for your help!

**Comment by twalpole** [comment]
Not a problem - you can see how the `link` selector is implanted her - https://github.com/teamcapybara/capybara/blob/master/lib/capybara/selector/definition/link.rb
