### ISSUE TITLE
Can't use Edge with selenium_chrome or selenium_chrome_headless ?

### ISSUE THREAD

**Issue by Ashvith** [teamcapybara/capybara#2360]
**Note:** This is for issues with Capybara.  If you have a howto type question, please ask on the mailing list as requested in the README: http://groups.google.com/group/ruby-capybara

## Meta
Capybara Version: 3.13.0
Driver Information (and browser if relevant): selenium-webdriver-3.142.7 with Microsoft Edge Version 83.0.478.37

## Expected Behavior
Should emulate the web browser test inside of new Edgium browser ,  when setting in :selenium_chrome as the default browser.

## Actual Behavior
You need to download the drivers for Google Chrome 
*forgive me , I am not currently on my PC , but yes , it looks something like this*

## Steps to reproduce
None ? In fact , I am using this for my Coursera assignment , and so , by kind of figuring it out , had a guess that I can switch drivers between Firefox (which is :selenium) to Chrome (:selenium_chrome).
I guess , maybe the Edge drivers are not added to the current stable ?
I need this because I don't want to keep multiple browsers in my PC , and because Chrome messes up my device (I'm in love with the new smooth Edgium), and Firefox , let's say , I don't want to work with non-Webkit engines

**Comment by twalpole** [comment]
Capybara provides builtin driver registrations for Firefox and Chrome because they're widely used and supported in a stable release of selenium-webdriver.  If you want to use MS Edge you will need to use a version of selenium-webdriver which supports it (4.0 alpha releases) and configure your own driver registration - https://github.com/teamcapybara/capybara/blob/master/README.md#configuring-and-adding-drivers .  In the future please ask howto questions on the mailing list (or stackoverflow) as requested at the top of the issue form.
