### ISSUE TITLE
#click does not always click

### ISSUE THREAD

**Issue by leoarnold** [teamcapybara/capybara#2375]
May be a continuation of #2343.

## Meta
Capybara Version: 3.33.0
Driver Information (and browser if relevant): apparition (0.6.0) with Chromium "Version 83.0.4103.61 (Official Build) Built on Ubuntu , running on Ubuntu 18.04 (64-bit)"

## Expected Behavior

Given an AngularJS 1.5.6 form

```html
  <form ng-submit="submit()" name="settingsForm" novalidate>
    <div class="row">
      <div id="message" class="small-12 columns">
        {{ message }}
      </div>
    </div>
    <div class="row">
      <div class="small-12 columns">
        <label>Email address
          <input type="email" name="client_email" ng-model="client.email">
        </label>
      </div>
    </div>
    <div class="button-container">
      <button type="submit">Submit</button>
    </div>
  </form>
```

and using RSpec and SitePrism
when I write a test with

```ruby
form.email.set('test@example.com')
form.save_button.click # save_button is the element identified by '[type="submit"]'

expect(form.message(wait: 10)).to have_text('Success!')
```

then I expect the JavaScript call `submit()` to run upon button click

## Actual Behavior

Even when I alter `submit` to

```js
$scope.submit = function() {
  console.log('Clicked!');
  $scope.message = 'Success!';
}
```

the expectation will fail in most (but not all) runs of the test. Whenever the test fails, the log does not show the message "Clicked!", indicating that the `submit` function was never called.

Similar behavior has been reported in #2343 and a [blog post from 2016](http://atodorov.org/blog/2016/05/31/capybaras-findclick-doesnt-always-fire-onclick/) by @atodorov using Poltergeist.

Curiously, as pointed out by @atodorov, using `trigger(:click)` in place of `click` seems to be a (literally) sure fire solution.

I tried `Capybara.disable_animation = true` from #2343 but this did not change anything.

**Comment by twalpole** [comment]
Capybara/apparition never "don't click" when you call click (unless they return an error). It will always generate a click, the question is whether the page is ready to process that click and where that click occurs.  To test this you can add a long sleep before calling click and see if the click becomes reliable then. If it does then it means you need an assertion before the click that checks for something that indicates the page is actually ready to be interacted with.  The other possibility is that your page is animating something and the position calculated for where the click should happen changes before the event is actually processed. Capybara provides the `disable_animation` animation as a convenience that attempts to disable animations but there is no way it can know everything happening on your page and therefore it's not foolproof (Especially if you're using JS driven animation rather than CSS).  You're always going to be better off directly disabling animations via whatever libraries you're using on your page to do the animation.

**Comment by leoarnold** [comment]
Thanks, I'll investigate and come back to this.

Just for clarity: What does `trigger(:click)` do then? Does it trigger the `onClick` event without actually clicking?

**Comment by twalpole** [comment]
It calls the click handler directly via JS - really should only be used when web scraping , not testing because it does not replicate user action
