### ISSUE TITLE
disable_animation injected script causes XHTML parsing error

### ISSUE THREAD

**Issue by dmorgan-fa** [teamcapybara/capybara#2425]
Hi, I recently ran into some issues when enabling the `disable_animation` option:

https://github.com/teamcapybara/capybara/blob/f43b6499ecb2721dd97b63a7fe31ff2518b89b4c/lib/capybara/server/animation_disabler.rb#L47

The above line causes XHTML pages to incur a parsing error on the `defer` tag (see [here](https://monkeyraptor.johanpaul.net/2015/11/fixing-xhtml-parsing-error-on-chrome.html)) then on the logical `&&`.

Locally testing, I've found that the following resolves the issue: `<script defer="true">if (typeof jQuery !== 'undefined') {jQuery.fx.off = true};</script>`.

Some context around the issue:
While this might be limited in scope, it impacts some specs we have that are in place to provide support for a third party's import format.

Apologies, I'm unfamiliar with what's necessary to fully resolve this (PR, an appropriate test, etc.).

**Comment by twalpole** [comment]
I didn't realize anyone still cared about XHTML :).  Additionally, I'd say if you're running validators against your document during your tests, you probably shouldn't be running them against documents that test tools have injected markup/code into  - since it's not really validating what would be served to an end-user.

That being said the "correct" solution here (rather than changing the JS) is probably to wrap the script and inline style sections in commented CDATA.  That will mean if the JS/CSS is updated in the future it won't be an issue.  If you could submit a PR for that it'd be great.

**Comment by dmorgan-fa** [comment]
Thanks for the help @twalpole! That makes more sense as a solution.

I've created a PR, let me know if there's anything else I need to do 👍
