### ISSUE TITLE
Make have_current_path query string compare order independent

### ISSUE THREAD

**Issue by woto** [teamcapybara/capybara#2432]
Hi, is it possible to make `have_current_path` query string compare order independent?

The reason it is order dependent is that `have_current_path` compares urls like this
https://github.com/teamcapybara/capybara/blob/master/lib/capybara/queries/current_path_query.rb#L29
which is:
```
irb(main):040:0> ::Addressable::URI.parse('http://ya.ru?f1=1&f2=1') == ::Addressable::URI.parse('http://ya.ru?f1=1&f2=1')
=> true
irb(main):041:0> ::Addressable::URI.parse('http://ya.ru?f1=1&f2=1') == ::Addressable::URI.parse('http://ya.ru?f2=1&f1=1')
=> false
```

It is possible for example to use `normalized_query(:sorted)` maybe somehow optional using options like `ignore_query` https://github.com/teamcapybara/capybara/blob/master/lib/capybara/queries/current_path_query.rb#L14

```
irb(main):044:0> ::Addressable::URI.parse('http://ya.ru?f1=1&f2=1').normalized_query(:sorted)
=> "f1=1&f2=1"
irb(main):045:0> ::Addressable::URI.parse('http://ya.ru?f2=1&f1=1').normalized_query(:sorted)
=> "f1=1&f2=1"
```

Also found this issue:
https://github.com/sporkmonger/addressable/issues/28

Thank you

**Comment by twalpole** [comment]
While the URL query string often contains name=value parameters it's not actually required to by the URL spec (it's just the string between ? and # (or end of the url). Because of this it wouldn't be correct to change it to what you're asking for.  If you still need to check with order independence you could use the optional filter block - something like

    expect(page).to have_current_path('http://ya.ru', ignore_query: true) do |uri| 
       uri.normalized_query(:sorted) == "f1=1&f2=1"
    end
