### ISSUE TITLE
Isn't find_css supposed to work with the :rack_test driver?

### ISSUE THREAD

**Issue by texpert** [teamcapybara/capybara#2458]
## Meta
Capybara Version: 3.35.3

Driver Information (and browser if relevant):
:rack_test 

## Expected Behavior
`find_css` should be working

## Actual Behavior
```bash
     Failure/Error: find_css('.pagy-bootstrap-nav')
     
     NoMethodError:
       undefined method `find_css' for #<RSpec::ExampleGroups::HomePage::Layout::Table::WhenThereANumberOfFeedsDefinedMoreThanPagyVARSItems:0x00007fe74851dfb0>
       Did you mean?  find_all
     # ./spec/feauters/home_page_spec.rb:97:in `block (7 levels) in <top (required)>'
     # ./spec/feauters/home_page_spec.rb:85:in `block (6 levels) in <top (required)>'
     # ./spec/feauters/home_page_spec.rb:84:in `block (5 levels) in <top (required)>'

Finished in 0.26536 seconds (files took 2.63 seconds to load)
4 examples, 1 failure

Failed examples:

rspec ./spec/feauters/home_page_spec.rb:83 # Home page Layout table when there a number of feeds defined, more than Pagy::VARS[:items] has headers, feeds list rows qty equal to Pagy::VARS[:items], pagination widget, and a `New Feed` link
```

## Steps to reproduce
`bundle exec rspec spec/feauters/home_page_spec.rb ` on this app: `https://github.com/texpert/rails_6_rss_reader/tree/add-home-page-spec`

**Comment by twalpole** [comment]
`find_css` is a method on the driver and isn't meant for users.  You should be using `find(:css, <CSS>)` which can generally just be `find(<CSS>)` since :css is the default selector type.

Also looking at the project you linked to, you're doing a number of things that are considered bad practice/plain wrong when writing your tests.

For instance

```
 within(:xpath, './/body') do
          within('.container') do
            within('.navbar') do
              within('.navbar-nav-scroll') do
                within('.navbar-nav') do
                  find_link('Feeds', visible: :all).visible?
                  find_link('Posts', visible: :all).visible?
                end
              end
            end
          end
        end
```
1.  There's no need to nest all those withins - just do

```
 within('.container .navbar .navbar-nav-scroll .navbar-nav') do
   ...
 end
``` 
although specifying all those nested elements really is just making your selector brittle and it might be better to be a bit less specific if possible.

2.  `visible?` just returns a boolean so your `find_link('Feeds', visible: :all).visible?` really isn't checking anything
    Instead you should just be doing `expect(page).to have_link('Feeds')`

3.   `table_rows = find(:xpath, '.').all('tr') ...`
     If you're checking there are no rows it should just be `expect(page).not_to have_css('tr')` or to check for a certain number `expect(page).to have_css('tr', count: 4)`
 
   So 
```
within(:xpath, './/table/tbody') do
                table_rows = find(:xpath, '.').all('tr')
                expect(table_rows.size).to eql(Pagy::VARS[:items])
              end
```
 could just be written as `expect(page).to have_css('tbody tr', count: Page::VARS[:items])`

4.  You shouldn't be expecting on predicate methods because it defeats the retrying and produces useless failure messages when there's an issue 
    `expect(has_css?('.pagy-bootstrap-nav')).to be_falsey` should just be `expect(page).not_to have_css('.pagy-bootstrap-nav')`

5.  You shouldn't be using the "standard" rspec matches (eql, etc) with Capybara elements (again defeats the retrying - makes your tests more brittle)
    `expect(find(:xpath, './/table/caption').text).to eql('Feeds List')` should be `expect(page).to have_xpath('.//table/caption', text: 'Feeds List')`

6.  I don't know why you keep preceding `all` with `find(:xpath,  '.')`
    With Capybara included in the scope `headers = find(:xpath, '.').all('th').map(&:text)`  should just be `all('th').map(&:text)` or if you really want to call `all` on an object it could be `page.all('th')...`

**Comment by texpert** [comment]
Thank you very much for detailed explanation, @twalpole !

Though, `find_link` is perfectly failing when couldn't find the link:

```
     Failure/Error: find_link('Post', visible: :all, exact: true).visible?

     Capybara::ElementNotFound:
       Unable to find link "Post" within #<Capybara::Node::Element tag="ul" path="/html/body/div/div/div/ul">
```

**Comment by texpert** [comment]
As for `expect(page)`, I am testing elements to be at precise locations, not just in the page.

**Comment by twalpole** [comment]
> Thank you very much for detailed explanation, @twalpole !
> 
> Though, `find_link` is perfectly failing when couldn't find the link:
> 
> ```
>      Failure/Error: find_link('Post', visible: :all, exact: true).visible?
> 
>      Capybara::ElementNotFound:
>        Unable to find link "Post" within #<Capybara::Node::Element tag="ul" path="/html/body/div/div/div/ul">
> ```

Yes - but it wouldn't fail if the link was on the page but hidden (non-visible) - and since you're calling 'visible?' I assume you want to make sure it's visible which just calling `.visible?` won't do.

You could just write it as `find_link('Post', exact: true)`  - which would check for visibility but isn't as clear that you're actually setting an expectation as `expect(page).to have_link('Post', exact: true)`

**Comment by twalpole** [comment]
> As for `expect(page)`, I am testing elements to be at precise locations, not just in the page.

`page` is just an alias for `Capybara.current_session` which handles element scoping. So when you say `expect(page).to have_xxxx(....)` `page` effectively refers to the currently scoped element.  So inside a `within` call `page` will effectively evaluate to the scoped element so `expect(page)....` will do exactly what your previous code was trying to do.   

    within('#my_container') do
      expect(page).to have_link('Something') # `page` is the scoped section so this will only succeed if the link is within the element with id of 'my_container'
   end
