### ISSUE TITLE
status of headless tests on head?

### ISSUE THREAD

**Issue by josh-m-sharpe** [teamcapybara/capybara#2464]
It seems that c534325304c6dd876c2fc8a0be9516851e5ffa49 was introduced for emoji support(?) but it broke headless testing:  https://github.com/teamcapybara/capybara/pull/2409/files - I'm just curious if I've read all that right and if there's a path forward?  Thanks!

**Comment by twalpole** [comment]
@josh-m-sharpe headless should be fine as long as you're not sending Emoji currently -- the other PR is still open because the hope has been that Chrome/chromedriver would fix the issue they have - but it hasn't happened yet.  The other PR isn't a good solution either since it means keyboard events wouldn't be generated which could break a number of apps.
