### ISSUE TITLE
Feature request: checkbox would be findable according to its title

### ISSUE THREAD

**Issue by deepj** [teamcapybara/capybara#2538]
## Meta
Capybara Version: 3.36.0

## Expected Behavior

Calling in tests
```
check('Check all checbox')
```

would find this checkbox

```ruby
<input type="checkbox" name="check-all" title="Check all checkbox">
```

This checkbox is without label.

## Actual Behavior

```html
Capybara::ElementNotFound: Unable to find checkbox "Check all checkbox" that is not disabled
```

## Steps to reproduce

See above

**Comment by twalpole** [comment]
Capybara matches the locator for fields (including checkbox) against id, name, or associated label text - Since this is the first time `title` has been requested it would likely be a performance penalty paid by everyone that would benefit very few, and as such isn't likely to be added in the short term.  If you want `title` matching in your own project you could monkey patch the locate_field method or just add a `title` filter to the `field` selector by doing something like

    Capybara.modify_selector :field do
       expression_filter(:title) do |expr, title|
         expr[Xpath.attr(:title) == title.to_s]
       end
    end

which should then allow you to do `check(title: 'Check all checkbox')`
