### ISSUE TITLE
[Feature request] Add `:last` in addition to `:first` for `match`

### ISSUE THREAD

**Issue by boris-petrov** [teamcapybara/capybara#2575]
## Meta
Capybara Version:
3.37.1
Driver Information (and browser if relevant):
not relevant

## Expected Behavior
We currently have `:first` when using finders:

```rb
find('.class', exact_text: '1', match: :first)
```

Which is very convenient when there are multiple matches. It would also be nice to add a `:last` in these cases. Reason - for example, when I add things to a list in my app, I'll do something like:

```rb
click_button '+'
click_button 'edit'
...

click_button '+'
click_button 'edit'
```

However, the second call to `click_button 'edit'` won't work because there are two items now and hence two times `edit`. To click the first one I could use something like `find('button', exact_text: 'edit', match: :first).click` and that would work good. But to click the second (or third, or fourth...) I have to resort to other ways.

I believe it would be very useful to have `:last` for these finders.

**Comment by twalpole** [comment]
What's wrong with `all('button', exact_text: 'edit').last.click` ?  especially since if you're dynamically adding buttons to the page you'd need to verify that the new thing is actually on the page before clicking it, so you'd be doing something like

    all('button', exact_text: 'edit', count: the_new_expected_number_of_buttons).last.click

I don't think adding a :last match type really buys anything, and isn't worth the cost of maintaining

**Comment by boris-petrov** [comment]
@twalpole yes, that's what I currently do, but this has 2 main "problems":

1) it's slower, because `all` will find all buttons instead of just one (I guess `:first` and `:last` could be optimized to not find and return a million items unlike `all`);
2) it's not consistent with the other code which uses `:first`. It "looks" different and has different logic.

Both are minor issues of course, but still. Nevertheless, you're the maintainer so I'm fine with whatever you decide. :)

**Comment by twalpole** [comment]
1. Not really because to find the last you still have to get all the elements from the browser and check them to find the last, it MIGHT be quicker in some cases to reverse search the list but not guaranteed
2. If consistency in code look is your big issue here then rather than using match: :first when dealing with multiple elements write your code as 

    all('.class', exact_text: '1').first.click

which should be the same speed as the original since results are lazy evaluated
