### ISSUE TITLE
Capybara.string doesn't capture CSS classes containing ":"

### ISSUE THREAD

**Issue by esmale** [teamcapybara/capybara#2699]
## Meta
Capybara Version: 3.39.2

Driver Information (and browser if relevant): N/A, using Capybara.string

## Expected Behavior
Capybara should correctly capture/parse CSS classes that contain a ":" character.  I'm using Tailwind variants, which take the form of `css_class_1:css_class_2`.

```
html = "<div class="normal variant1:variant2">test</div>
Capybara.string(html).has_css?(".normal")  # ==> true
Capybara.string(html).has_css?(".variant1:variant2") # ==> true
```

## Actual Behavior
Capybara doesn't appear to parse or recognize classes that contain the ":" character.  They seem to be thrown away completely.

```
html = "<div class="normal_class variant_class:variant">test</div>
Capybara.string(html).has_css?(".normal") # ==> true
Capybara.string(html).has_css?(".variant1:variant2") # ==> false
Capybara.string(html).has_css?(".variant1") # ==> false
```

**Comment by twalpole** [comment]
Capybara.string is just a light wrapper around Nokogiri - so if this an issue for you please report it over at the Nokogiri project

**Comment by twalpole** [comment]
Actually, after thinking about this further the issue is because ".variant1:variant2" isn't a valid CSS selector.  For that to be a valid CSS selector you need to escape the : as `\3A ` which would mean

    ...has_css?(".variant1\\3A variant2")

or

    ...has_css?(".variant1\\3Avariant2")

the space after the 3A is only required if the following character is a valid hexadecimal character so in this case it can be dropped (v not in 0-9a-f)

You'll find the same issue if you try to use `.variant1:variant2` in CSS in a browser

**Comment by twalpole** [comment]
@esmale Note, there is an option if you don't want to do the escaping yourself which is to use the `class` option

    ....has_css?('*', class: 'variant1:variant2')

which can also receive an array for anding together multiple classess

    .....has_css?('*', class: ['normal', 'variant1:variant2'])
