### ISSUE TITLE
Tests Fail in CI with 'visit' Method but Pass Locally

### ISSUE THREAD

**Issue by davideluque** [teamcapybara/capybara#2741]
## Meta
Capybara Version:
3.40.0

Driver Information (and browser if relevant):
selenium-webdriver (4.11.0) with headless-chrome

-----------------------

I'm encountering a strange issue where my tests pass when run on my local machine, but fail when executed in the continuous integration (CI) environment. I'm working with GitHub Actions, utilizing the ubuntu-latest runner and Node 20. My development environment is on a Mac with an M1 chip, running the same version of Node.

Locally, my tests pass when using the `visit` method. However, in the CI environment, these tests only pass if I replace `visit` with `click_link`.

The screenshots from the CI runs suggest that the visit command isn't functioning as expected—it seems as though the command isn't being executed at all.

**Comment by twalpole** [comment]
Not a lot to go on here. I don't even really know how you would swap visit with click_link since one requires being passed a url and the other an element on the page.  most likely it's a case of you not visiting the correct hostname but without any examples, test code, etc no way to say.

**Comment by jgarber623** [comment]
> [!NOTE]
> My comments below are informational for anyone who (like me) is experiencing some version of this issue. I don't have enough evidence to provide to support re-opening this issue.

Hello! I recognize this issue was closed back in January, but I'd like to add my recent experience with what _looks like_ issues similar to the original report here.

Beginning on 24 September 2024, I began noticing seemingly random system test failures in CI (GitHub Actions, in this case) on an app I manage. Tests that had passed earlier in the day began failing.

The _one_ difference I was able to find? GitHub began rolling out updates to their `ubuntu-latest` runner image that, among many other things, included an update to Chrome and chromedriver from v128 to v129 ([release notes](https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20240922.1)).

My local app and environment is/was using:

- chromium and chromedriver v128.0.6613.119-r0
- capybara v3.40.0
- selenium-webdriver v4.25.0
- rails 7.1.4
- most up-to-date rspec and rspec-rails

Admittedly, there's a gap between my local environment (running in an Alpine Linux Dev Container) and GitHub Actions _and_ I unfortunately can't share the app's code. So, apologies for that.

After ~two days of experimentation and playing wack-a-mole with intermittently failing specs, I still can't entirely point to a precise root cause.

_However_, I'm currently having a bit of success switching _some_ specs from using, say, `visit "/api_applications"` to commands like `within(".main-nav") { click_link "API Applications" }`. Certain specs that use `visit` seem to work just fine while others have become flaky.

All that's to say, I'm not entirely sure the issues I'm experiencing are Capybara-related. The _most obvious_ change was the Chrome/chromedriver v128 to v129 update which makes me suspicious that something in _that_ update is behaving badly.

…and, as of this posting, the version of Chrome/chromedriver running in GitHub's `ubuntu-latest` image isn't even up-to-date. Newest v129 version is `129.0.6668.70`. 🤷🏻
