### ISSUE TITLE
No option to leave browser open at end of running test

### ISSUE THREAD

**Issue by oldfartdeveloper** [teamcapybara/capybara#42]
I see that lib/capybara/driver/selenium_driver.rb, line 72, closes the browser on exit.  It would be convenient to have a command line argument that would not do the close so that you could see the results of method calls such as 'save_and_open_page'.

**Comment by mhluska** [comment]
There really should be an answer for this besides "put a debugger where it fails". One reason is the code might not fail every single time at that particular line (either due to sporadic errors or helper functions that are called in different contexts).

**Comment by twalpole** [comment]
@mhluska This issue was closed almost 8 years ago - It's not really the place to make this request.  Additionally with most test frameworks it's easy enough to insert some type of after hook, before the session is reset, where you can tell if the test failed and do whatever you want (run a debugger, etc)

**Comment by mhluska** [comment]
I got you. But people still land here as I did through Google looking for an answer. So maybe we should provide something concrete even though a lot of time has passed.
